// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sol contributors.

/* style.h — Sol's main-window stylesheet + presentation defaults.
 *
 * Keep style edits in this single header to iterate quickly without
 * touching layout/logic code in the .c modules.
 */

#ifndef SOL_UI_STYLE_H
#define SOL_UI_STYLE_H

#include "sol_ui_constants.h"

/* Window presentation defaults. */
#define SOL_UI_WINDOW_TITLE  "Sol"
#define SOL_UI_WINDOW_WIDTH  1080
#define SOL_UI_WINDOW_HEIGHT 720

/* Split bar presentation defaults. */
#define SOL_UI_SPLIT_BAR_SIZE        1.0f
#define SOL_UI_SPLIT_BAR_COLOR       ca_color(0.22f, 0.24f, 0.30f, 1.0f)
#define SOL_UI_SPLIT_BAR_HOVER_COLOR ca_color(0.34f, 0.37f, 0.47f, 1.0f)

/* ------------------------------------------------------------------
 * Main window CSS for Sol.
 *
 * Conventions:
 *   - All corners are square (no border-radius anywhere).
 *   - Colors use #rrggbb hex; semi-transparent overlays use rgba().
 *   - Font sizes route through SOL_UI_BOOT_FONT_SIZE_PX_CSS to keep
 *     them in lockstep with the runtime default.
 * ------------------------------------------------------------------ */
static const char *SOL_UI_MAIN_WINDOW_CSS =
    /* ===== Root + workspace shell ===== */
    ".app-root {"
    "  background: #0c0e13;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-host {"
    "  background: #11151f;"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-full {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-content {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-buffer-area {"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* ===== Left file tree panel ===== */
    ".tree-panel {"
    "  background: #0d1019;"
    "  width: 240px;"
    "  height: 100%;"
    "  min-width: 240px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 6px 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  border-right-width: 1px;"
    "  border-right-color: #1c2235;"
    "  overflow: hidden;"
    "}"
    ".tree-header {"
    "  color: #98a4c2;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 6px 12px 10px 12px;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 24px;"
    "  padding: 0px 10px;"
    "  gap: 6px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  text-color: #c0c8de;"
    "}"
    ".tree-row:hover { background: #1a2236; }"
    ".tree-indent {"
    "  height: 1px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".tree-glyph {"
    "  color: #5d6f8d;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 12px;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-glyph-dir {"
    "  color: #98a4c2;"
    "}"
    ".tree-icon {"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 16px;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-icon-dir { color: #d8a85a; }"
    ".tree-name {"
    "  color: #c0c8de;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".tree-name-dir {"
    "  color: #e6ecff;"
    "}"
    /* ===== Buffer panes ===== */
    ".buffer-pane {"
    "  background: #171c2a;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".buffer-pane-active {"
    "  background: #20283a;"
    "}"
    /* ===== Tab strip (one row per buffer pane) ===== */
    ".buffer-tabs-row {"
    "  width: 100%;"
    "  height: 28px;"
    "  background: #0a0d14;"
    "  padding: 0px 4px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  border-bottom-width: 1px;"
    "  border-bottom-color: #1c2235;"
    "  overflow: hidden;"
    "}"
    ".buffer-tab {"
    "  background: transparent;"
    "  height: 28px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "  border-right-width: 1px;"
    "  border-right-color: #1c2235;"
    "}"
    ".buffer-tab-active {"
    "  background: #20283a;"
    "}"
    ".buffer-tab-text {"
    "  color: #6b7591;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".buffer-tab-text-active {"
    "  color: #e6ecff;"
    "}"
    ".buffer-body {"
    "  background: #0f1320;"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    /* Inner row: text column on the left, custom scrollbar on the right. */
    ".buffer-scroll-row {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  gap: 0px;"
    "  padding: 0px;"
    "  overflow: hidden;"
    "}"
    ".buffer-text-col {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 8px;"
    "  gap: 0px;"
    "  overflow: hidden;"
    "}"
    /* Left gutter: shows the line number for each visible row.
       Width is fixed in CSS so the text column lines up no matter how
       large the line numbers get for short files. Long files (1e6+ lines)
       will overflow this gutter; that's acceptable for now. */
    ".buffer-gutter-col {"
    "  width: 56px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 8px 8px 8px 8px;"
    "  gap: 0px;"
    "  background: #0c1019;"
    "  border-right-width: 1px;"
    "  border-right-color: #1c2235;"
    "  overflow: hidden;"
    "  align-items: flex-end;"
    "}"
    ".buffer-gutter-line {"
    "  color: #4a5572;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "}"
    ".buffer-gutter-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-line {"
    "  color: #d7deef;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    /* Per-line row used for every line. Each row contains a single
       full-width ca_text. The active line additionally emits an
       absolutely-positioned caret div which sits on top of the text
       without disturbing flex flow — so cursor and non-cursor lines
       have IDENTICAL layout and text never shifts. */
    ".buffer-line-row {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "}"
    ".buffer-caret {"
    "  width: 2px;"
    "  height: 18px;"
    "  background: #c8d0ff;"
    "  flex-shrink: 0;"
    "}"
    /* Transparent button wrapping each visible line. Clicks anywhere on
       the row focus the host pane and reposition the cursor. */
    ".buffer-line-btn {"
    "  width: 100%;"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  background: rgba(0, 0, 0, 0);"
    "  padding: 0px;"
    "  gap: 0px;"
    "}"
    /* Custom virtual scrollbar — vertical column with a top spacer,
       a thumb, and a flex-grow filler. Heights are computed in C. */
    ".buffer-scrollbar {"
    "  width: 10px;"
    "  height: 100%;"
    "  background: rgba(255, 255, 255, 0.04);"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "}"
    ".buffer-scrollbar-spacer {"
    "  width: 10px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-scrollbar-thumb {"
    "  width: 10px;"
    "  background: rgba(255, 255, 255, 0.28);"
    "  border-radius: 5px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-scrollbar-thumb-active {"
    "  background: rgba(255, 255, 255, 0.55);"
    "}"
    ".buffer-body-text {"
    "  color: #d7deef;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    /* ===== Command Flow popup (floating bottom-right which-key) ===== */
    /* Transparent absolute overlay covering the whole content area.
       align-items: flex-end + justify-content: flex-end push the panel
       to the bottom-right corner regardless of window size. */
    ".cf-overlay {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px 0px 0px 0px;"
    "  gap: 0px;"
    "  justify-content: flex-end;"
    "  align-items: flex-end;"
    "  overflow: hidden;"
    "}"
    ".cf-panel {"
    "  background: #0d1117;"
    "  border-color: #1e2a3d;"
    "  border-width: 1px;"
    "  padding: 6px 6px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".cf-row {"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 2px 6px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".cf-row-error { background: #1c1418; }"
    ".cf-row-key {"
    "  background: #16243a;"
    "  width: 28px;"
    "  height: 18px;"
    "  padding: 0px 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".cf-row-key-text {"
    "  color: #58b8f0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "  width: 100%;"
    "}"
    ".cf-row-label {"
    "  color: #c8d6ee;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".cf-row-label-error { color: #c07585; }"
    ".cf-row-more {"
    "  color: #5b6c84;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: right;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".cf-empty {"
    "  color: #3f5070;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 4px 6px;"
    "}"
    /* ===== File picker (separate window) ===== */
    ".fp-root {"
    "  background: #0c0e13;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".fp-host {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".fp-header {"
    "  background: #11151f;"
    "  width: 100%;"
    "  height: 38px;"
    "  padding: 6px 12px;"
    "  gap: 10px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-bottom-width: 1px;"
    "  border-bottom-color: #1c2235;"
    "  overflow: hidden;"
    "}"
    ".fp-up {"
    "  background: #1a2236;"
    "  width: 28px;"
    "  height: 26px;"
    "  padding: 0px 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "}"
    ".fp-up:hover { background: #243150; }"
    ".fp-up-text {"
    "  color: #d8e0f4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "}"
    ".fp-path {"
    "  color: #d8e0f4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".fp-list {"
    "  background: #0d1019;"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  padding: 6px 0px;"
    "  gap: 0px;"
    "  overflow: hidden;"
    "}"
    ".fp-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 26px;"
    "  padding: 0px 14px;"
    "  gap: 10px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  text-color: #c0c8de;"
    "}"
    ".fp-row:hover { background: #1a2236; }"
    ".fp-glyph {"
    "  color: #6c7da0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 18px;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".fp-glyph-dir { color: #d8a85a; }"
    ".fp-name {"
    "  color: #c0c8de;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".fp-name-dir { color: #e6ecff; }"
    ".fp-empty {"
    "  color: #3f5070;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 8px 14px;"
    "}"
    ".fp-footer {"
    "  background: #11151f;"
    "  width: 100%;"
    "  height: 48px;"
    "  padding: 8px 12px;"
    "  gap: 10px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-end;"
    "  align-items: center;"
    "  border-top-width: 1px;"
    "  border-top-color: #1c2235;"
    "  overflow: hidden;"
    "}"
    ".fp-action {"
    "  background: #1a2236;"
    "  height: 30px;"
    "  padding: 0px 18px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "}"
    ".fp-action:hover { background: #243150; }"
    ".fp-action-primary {"
    "  background: #2a5e8c;"
    "}"
    ".fp-action-primary:hover { background: #3573a8; }"
    ".fp-action-text {"
    "  color: #e6ecff;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: center;"
    "}"
    /* ===== Status bar ===== */
    ".status-bar {"
    "  background: #0b111e;"
    "  width: 100%;"
    "  height: 22px;"
    "  border-top-width: 0px;"
    "  padding: 0px 8px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".status-bar-left {"
    "  width: 100%;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  gap: 6px;"
    "  overflow: hidden;"
    "}"
    ".status-bar-value {"
    "  width: auto;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge {"
    "  width: 14px;"
    "  height: 14px;"
    "  justify-content: center;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge-key     { background: #21476f; }"
    ".status-bar-badge-command { background: #2a5e46; }"
    ".status-bar-badge-leader  { background: #665023; }"
    ".status-bar-badge-text {"
    "  color: #d8e6f6;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    ".status-bar-text {"
    "  color: #9fb6d8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: left;"
    "  width: auto;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}";

#endif /* SOL_UI_STYLE_H */
