// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sol contributors.

/* style.h — Sol's main-window stylesheet + presentation defaults.
 *
 * Keep style edits in this single header to iterate quickly without
 * touching layout/logic code in the .c modules.
 */

#ifndef SOL_UI_STYLE_H
#define SOL_UI_STYLE_H

#include "sol_ui_constants.h"

/* Window presentation defaults. */
#define SOL_UI_WINDOW_TITLE  "Sol"
#define SOL_UI_WINDOW_WIDTH  1080
#define SOL_UI_WINDOW_HEIGHT 720

/* Split bar presentation defaults. */
#define SOL_UI_SPLIT_BAR_SIZE        3.0f
#define SOL_UI_SPLIT_BAR_COLOR       ca_color(0.11f, 0.11f, 0.13f, 1.0f)
#define SOL_UI_SPLIT_BAR_HOVER_COLOR ca_color(0.30f, 0.34f, 0.42f, 1.0f)

/* ------------------------------------------------------------------
 * Retro dark theme for Sol.
 *
 * Visual system:
 *   - Raised widgets: bright top+left bevel, dark bottom+right shadow.
 *   - Inset/depressed areas: dark top+left, bright bottom+right.
 *   - 0px corner radius everywhere — sharp edges, classic retro feel.
 *   - Chunky 14px scrollbar track with raised thumb.
 *   - Steel-blue accent; charcoal base; no green or brown chrome.
 *
 * Palette (reference):
 *   deep bg     #0e0e10   very dark void
 *   app bg      #18181c   main workspace surface
 *   panel bg    #1e1e24   sidebar / panel background
 *   raised face #2a2a32   button / toolbar face
 *   inset deep  #0c0c0e   text editor / input well
 *   bevel hi    #4c4c58   top+left highlight edge
 *   bevel sh    #070709   bottom+right shadow edge
 *   active sel  #182e50   selected row / active tab fill
 *   accent      #3d6d9a   steel-blue accent
 *   accent hi   #5588b8   hover accent
 *   text bright #c8c8cc   primary text
 *   text muted  #747480   secondary labels
 *   text dim    #444450   disabled / placeholders
 * ------------------------------------------------------------------ */
static const char *SOL_UI_MAIN_WINDOW_CSS =
    /* ===== Root + workspace shell ===== */
    ".app-root {"
    "  background: #0e0e10;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-host {"
    "  background: #18181c;"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-full {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-content {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-buffer-area {"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* ===== Left file tree panel ===== */
    ".tree-panel {"
    "  background: #1e1e24;"
    "  width: 100%;"
    "  height: 100%;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "  border-right: 2px #070709;"
    "}"
    /* Sticky section header */
    ".tree-section-header {"
    "  background: #242430;"
    "  width: 100%;"
    "  height: 26px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "  border-top: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "}"
    ".tree-section-title {"
    "  color: #5a5a6a;"
    "  font-size: 10px;"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "}"
    /* Scrollable list container */
    ".tree-scroll-area {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 2px 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    ".tree-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0px 6px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "}"
    ".tree-row:hover { background: #262630; }"
    /* Root folder label row */
    ".tree-root-row {"
    "  background: #242430;"
    "  width: 100%;"
    "  height: 24px;"
    "  padding: 0px 8px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-top: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "}"
    /* Indent spacer */
    ".tree-indent {"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    /* Disclosure chevron */
    ".tree-arrow {"
    "  color: #4a4a58;"
    "  font-size: 10px;"
    "  width: 14px;"
    "  flex-shrink: 0;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-arrow-open { color: #6868a0; }"
    /* Icon column */
    ".tree-icon {"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 16px;"
    "  flex-shrink: 0;"
    "  margin-right: 5px;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-icon-dir-closed { color: #3d5e9a; }"
    ".tree-icon-dir-open   { color: #5578c0; }"
    ".tree-icon-file       { color: #404050; }"
    ".tree-icon-c          { color: #5a8ab0; }"
    ".tree-icon-h          { color: #a070c0; }"
    ".tree-icon-py         { color: #8aaa60; }"
    ".tree-icon-js         { color: #c8a840; }"
    ".tree-icon-ts         { color: #5a8ab0; }"
    ".tree-icon-json       { color: #b06048; }"
    ".tree-icon-html       { color: #a05838; }"
    ".tree-icon-css        { color: #5a8888; }"
    ".tree-icon-md         { color: #607080; }"
    ".tree-icon-cmake      { color: #907030; }"
    /* Name label */
    ".tree-name {"
    "  color: #9898a4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".tree-name-dir {"
    "  color: #b0b8c8;"
    "}"
    /* ===== Sticky ancestor headers ===== */
    ".tree-sticky-host {"
    "  padding: 0;"
    "  gap: 0;"
    "}"
    ".tree-sticky-row {"
    "  background: #202028;"
    "  z-index: 5;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0 6px;"
    "  gap: 0;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  border-bottom: 1px #070709;"
    "  border-left: 2px #3d6d9a;"
    "}"
    ".tree-sticky-row:hover {"
    "  background: #262630;"
    "}"
    /* ===== Buffer panes ===== */
    ".buffer-pane {"
    "  background: #151518;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".buffer-pane-active {"
    "  background: #18181e;"
    "}"
    /* ===== Tab strip ===== */
    ".buffer-tabs-row {"
    "  width: 100%;"
    "  height: 28px;"
    "  background: #1e1e26;"
    "  padding: 3px 4px 0px 4px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: flex-end;"
    "  justify-content: flex-start;"
    "  border-top: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  overflow: hidden;"
    "}"
    /* Inactive tab — raised, sitting above the strip */
    ".buffer-tab {"
    "  background: #282832;"
    "  height: 24px;"
    "  padding: 0px 3px 0px 10px;"
    "  gap: 4px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "  border-top: 1px #505060;"
    "  border-left: 1px #505060;"
    "  border-right: 1px #070709;"
    "}"
    /* Active tab — depressed/merged look, same bg as buffer body */
    ".buffer-tab-active {"
    "  background: #0d0d11;"
    "  border-top: 1px #070709;"
    "  border-left: 1px #070709;"
    "  border-right: 1px #505060;"
    "}"
    ".buffer-tab-text {"
    "  color: #585868;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".buffer-tab-text-active {"
    "  color: #c8c8d0;"
    "}"
    ".buffer-tab-close {"
    "  background: transparent;"
    "  width: 16px;"
    "  height: 16px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "  border-radius: 0px;"
    "  z-index: 1;"
    "}"
    ".buffer-tab-close:hover {"
    "  background: #3a1e1e;"
    "}"
    ".buffer-tab-close-icon {"
    "  color: #3a3a4a;"
    "  font-size: 11px;"
    "}"
    ".buffer-tab-close-icon-active {"
    "  color: #686878;"
    "}"
    /* Text area body — deeply inset "screen" look */
    ".buffer-body {"
    "  background: #0d0d11;"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "  border-right: 2px #3c3c48;"
    "}"
    /* Inner row: text column on the left, scrollbar on the right */
    ".buffer-scroll-row {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  gap: 0px;"
    "  padding: 0px;"
    "  overflow: hidden;"
    "}"
    ".buffer-text-col {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 8px;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow-x: hidden;"
    "  overflow-y: hidden;"
    "}"
    /* Left gutter */
    ".buffer-gutter-col {"
    "  width: 56px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 8px 8px 8px 8px;"
    "  gap: 0px;"
    "  background: #0a0a0d;"
    "  border-right: 2px #070709;"
    "  overflow: hidden;"
    "  align-items: flex-end;"
    "}"
    ".buffer-gutter-line {"
    "  color: #3a3a48;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "}"
    ".buffer-gutter-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-line {"
    "  color: #c4c4cc;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Highlight token classes */
    ".hl-plain   { color: #c4c4cc; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-keyword   { color: #c792ea; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-comment   { color: #546e7a; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-string    { color: #c3e88d; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-number    { color: #f78c6c; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-type      { color: #ffcb6b; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-function  { color: #82aaff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-property  { color: #89ddff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-macro     { color: #ffb62c; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-tag       { color: #f07178; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-attribute { color: #bb80b3; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-regex     { color: #ff5370; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-escape    { color: #ff9d57; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-namespace { color: #b2ccd6; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-label       { color: #c17e70; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-parameter   { color: #b8d0e8; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-constant    { color: #edc58a; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-operator    { color: #89ddff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-constructor { color: #82d7c0; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".buffer-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    /* Per-line row */
    ".buffer-line-row {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow: hidden;"
    "}"
    ".buffer-line-content {"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow: visible;"
    "}"
    /* Selection highlight */
    ".buffer-selection {"
    "  height: 20px;"
    "  background: #182e50;"
    "}"
    /* Caret — driven by Ca_DivDesc fields, CSS is a no-op anchor */
    ".buffer-caret {}"
    /* Transparent button wrapping each visible line */
    ".buffer-line-btn {"
    "  width: 100%;"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  background: rgba(0, 0, 0, 0);"
    "  padding: 0px;"
    "  gap: 0px;"
    "}"
    /* ===== Custom vertical scrollbar (retro chunky style) ===== */
    ".buffer-scrollbar {"
    "  width: 14px;"
    "  height: 100%;"
    "  background: #0c0c0f;"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-top: 1px #070709;"
    "  border-left: 1px #070709;"
    "  border-bottom: 1px #3c3c48;"
    "  border-right: 1px #3c3c48;"
    "}"
    ".buffer-scrollbar-spacer {"
    "  width: 14px;"
    "  flex-shrink: 0;"
    "}"
    /* Raised scrollbar thumb */
    ".buffer-scrollbar-thumb {"
    "  width: 14px;"
    "  background: #2e2e38;"
    "  border-radius: 0px;"
    "  flex-shrink: 0;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".buffer-scrollbar-thumb-active {"
    "  background: #3a3a46;"
    "}"
    ".buffer-hscrollbar {"
    "  background: #0c0c0f;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-top: 1px #070709;"
    "  border-left: 1px #070709;"
    "  border-bottom: 1px #3c3c48;"
    "  border-right: 1px #3c3c48;"
    "  z-index: 3;"
    "}"
    ".buffer-hscrollbar-spacer {"
    "  height: 14px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-hscrollbar-thumb {"
    "  height: 14px;"
    "  background: #2e2e38;"
    "  border-radius: 0px;"
    "  flex-shrink: 0;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".buffer-hscrollbar-thumb-active {"
    "  background: #3a3a46;"
    "}"
    ".buffer-body-text {"
    "  color: #c4c4cc;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    /* ===== Command Flow popup ===== */
    ".cf-overlay {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px 0px 0px 0px;"
    "  gap: 0px;"
    "  justify-content: flex-end;"
    "  align-items: flex-end;"
    "  overflow: hidden;"
    "}"
    ".cf-panel {"
    "  background: #22222c;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "  padding: 6px 6px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".cf-row {"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 2px 6px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".cf-row-error { background: #1c1018; }"
    /* Key badge — raised small button */
    ".cf-row-key {"
    "  background: #2a2a36;"
    "  width: 28px;"
    "  height: 18px;"
    "  padding: 0px 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  overflow: hidden;"
    "  border-top: 1px #4c4c58;"
    "  border-left: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "  border-right: 1px #070709;"
    "}"
    ".cf-row-key-text {"
    "  color: #4898c8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "  width: 100%;"
    "}"
    ".cf-row-label {"
    "  color: #b0b0bc;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".cf-row-label-error { color: #b06878; }"
    ".cf-row-more {"
    "  color: #505060;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: right;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".cf-empty {"
    "  color: #404050;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 4px 6px;"
    "}"
    /* ===== File picker ===== */
    ".fp-root {"
    "  background: #14141a;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".fp-host {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    /* Toolbar — raised chrome bar */
    ".fp-toolbar {"
    "  background: #22222c;"
    "  width: 100%;"
    "  height: 32px;"
    "  padding: 0px 4px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-top: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  overflow: hidden;"
    "}"
    /* Up / parent button */
    ".fp-up-btn {"
    "  background: #282832;"
    "  width: 26px;"
    "  height: 26px;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  margin-right: 4px;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".fp-up-btn:hover { background: #323244; }"
    ".fp-up-btn-active {"
    "  background: #1c1c24;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #4c4c58;"
    "  border-right: 2px #4c4c58;"
    "}"
    ".fp-up-icon {"
    "  color: #545468;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "}"
    ".fp-up-icon-active { color: #5a98c0; }"
    /* Breadcrumb */
    ".fp-breadcrumb {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "  overflow-x: hidden;"
    "  overflow-y: hidden;"
    "}"
    ".fp-crumb-btn {"
    "  background: transparent;"
    "  height: 24px;"
    "  padding: 0px 5px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "}"
    ".fp-crumb-btn:hover { background: #262630; }"
    ".fp-crumb-btn-active { background: transparent; }"
    ".fp-crumb-text {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-crumb-text-active {"
    "  color: #9898a8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-crumb-sep {"
    "  color: #30303e;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 12px;"
    "  flex-shrink: 0;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    /* Scrollable file list — inset well */
    ".fp-list {"
    "  background: #101014;"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  padding: 2px 0px;"
    "  gap: 0px;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    /* File / directory rows */
    ".fp-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "}"
    ".fp-row:hover { background: #20202a; }"
    ".fp-row-name {"
    "  color: #9898a8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".fp-row-name-dir { color: #a8b0c4; }"
    ".fp-empty {"
    "  color: #383848;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 14px 16px;"
    "}"
    /* Footer — raised chrome bar */
    ".fp-footer {"
    "  background: #22222c;"
    "  width: 100%;"
    "  height: 46px;"
    "  padding: 0px 12px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-top: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  overflow: hidden;"
    "}"
    /* Cancel button — raised */
    ".fp-action-cancel {"
    "  background: #28283a;"
    "  height: 28px;"
    "  padding: 0px 16px;"
    "  border-radius: 0px;"
    "  color: #a8a8b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  align-self: center;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".fp-action-cancel:hover { background: #323248; }"
    /* Primary action button — raised, accent tinted */
    ".fp-action-primary {"
    "  background: #1c3460;"
    "  height: 28px;"
    "  padding: 0px 16px;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  align-self: center;"
    "  border-top: 2px #3060a0;"
    "  border-left: 2px #3060a0;"
    "  border-bottom: 2px #0a1530;"
    "  border-right: 2px #0a1530;"
    "}"
    ".fp-action-primary:hover { background: #24407a; }"
    /* Thin vertical separator between toolbar button groups */
    ".fp-toolbar-sep {"
    "  width: 1px;"
    "  height: 16px;"
    "  background: #0e0e14;"
    "  flex-shrink: 0;"
    "  margin-right: 3px;"
    "  margin-left: 3px;"
    "}"
    /* Inline new-folder creation bar */
    ".fp-new-folder-bar {"
    "  background: #1e1e28;"
    "  width: 100%;"
    "  height: 36px;"
    "  padding: 0px 10px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-top: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "  overflow: hidden;"
    "}"
    ".fp-new-folder-label {"
    "  color: #666678;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Folder name text input — inset */
    ".fp-new-folder-input {"
    "  flex-grow: 1;"
    "  min-width: 80px;"
    "  height: 24px;"
    "  color: #b8c8e0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  background: #0c0c10;"
    "  border-radius: 0px;"
    "  padding: 0px 8px;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "  border-right: 2px #3c3c48;"
    "}"
    /* Small create/cancel buttons inside the new-folder bar */
    ".fp-nf-create {"
    "  background: #1c3460;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  border-top: 2px #3060a0;"
    "  border-left: 2px #3060a0;"
    "  border-bottom: 2px #0a1530;"
    "  border-right: 2px #0a1530;"
    "}"
    ".fp-nf-create:hover { background: #24407a; }"
    ".fp-nf-cancel {"
    "  background: #28283a;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  border-radius: 0px;"
    "  color: #a8a8b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".fp-nf-cancel:hover { background: #323248; }"
    /* Footer left info text */
    ".fp-footer-count {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Spacer */
    ".fp-footer-spacer {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "}"
    /* New Folder button in footer */
    ".fp-action-new-folder {"
    "  background: #22222e;"
    "  height: 28px;"
    "  padding: 0px 10px;"
    "  border-radius: 0px;"
    "  color: #505060;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  border-top: 2px #3c3c48;"
    "  border-left: 2px #3c3c48;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".fp-action-new-folder:hover { background: #2c2c3e; color: #6868a0; }"
    ".fp-action-new-folder-active {"
    "  background: #1a1a26;"
    "  color: #5a90c0;"
    "}"
    /* Sortable column header */
    ".fp-colhdr {"
    "  background: #1a1a22;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  border-top: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "  overflow: hidden;"
    "}"
    ".fp-colhdr-icon-gap {"
    "  width: 21px;"
    "  flex-shrink: 0;"
    "}"
    ".fp-colhdr-name-cell {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-size-cell {"
    "  width: 72px;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-date-cell {"
    "  width: 112px;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-btn {"
    "  width: 100%;"
    "  height: 22px;"
    "  background: transparent;"
    "  padding: 0px 4px;"
    "  gap: 4px;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "}"
    ".fp-colhdr-btn:hover { background: #222232; }"
    ".fp-colhdr-btn-active { background: transparent; }"
    ".fp-colhdr-btn-end {"
    "  width: 100%;"
    "  height: 22px;"
    "  background: transparent;"
    "  padding: 0px 4px;"
    "  gap: 4px;"
    "  justify-content: flex-end;"
    "  align-items: center;"
    "}"
    ".fp-colhdr-btn-end:hover { background: #222232; }"
    ".fp-colhdr-text {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-colhdr-text-active { color: #7898b8; }"
    ".fp-colhdr-sort-arrow {"
    "  color: #7898b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    /* Per-row metadata columns */
    ".fp-row-size {"
    "  color: #3e3e50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 72px;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "}"
    ".fp-row-date {"
    "  color: #3e3e50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 112px;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "  padding-right: 4px;"
    "}"
    /* ===== Status bar — inset groove at the bottom ===== */
    ".status-bar {"
    "  background: #111118;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0px 8px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "  border-top: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "}"
    ".status-bar-left {"
    "  width: 100%;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  gap: 6px;"
    "  overflow: hidden;"
    "}"
    ".status-bar-value {"
    "  width: auto;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge {"
    "  width: 14px;"
    "  height: 14px;"
    "  justify-content: center;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge-key     { background: #163254; }"
    ".status-bar-badge-command { background: #1c3c30; }"
    ".status-bar-badge-leader  { background: #3e3010; }"
    ".status-bar-badge-text {"
    "  color: #b0c8e0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    ".status-bar-text {"
    "  color: #787898;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: left;"
    "  width: auto;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    /* ===== Welcome screen ===== */
    ".welcome-pane {"
    "  background: #14141a;"
    "  width: 100%;"
    "  height: 100%;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 48px 64px;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".welcome-title {"
    "  color: #c0c0cc;"
    "  font-size: 22px;"
    "  text-wrap: nowrap;"
    "}"
    ".welcome-subtitle {"
    "  color: #404050;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  padding: 4px 0px 28px 0px;"
    "}"
    ".welcome-section {"
    "  width: auto;"
    "  gap: 2px;"
    "  padding: 0px 0px 20px 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-section-label {"
    "  color: #3c3c50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  padding: 0px 0px 6px 0px;"
    "}"
    ".welcome-row {"
    "  width: auto;"
    "  height: 20px;"
    "  gap: 12px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-key {"
    "  color: #4888c0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  width: 112px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".welcome-desc {"
    "  color: #70708c;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    /* Welcome action buttons */
    ".welcome-actions {"
    "  flex-direction: row;"
    "  gap: 8px;"
    "  padding: 0px 0px 20px 0px;"
    "  flex-wrap: wrap;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-btn {"
    "  padding: 6px 16px;"
    "  background: #26263a;"
    "  border-radius: 0px;"
    "  color: #a0a0b4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".welcome-btn:hover { background: #303050; }"
    ".welcome-btn-primary {"
    "  padding: 6px 16px;"
    "  background: #1c3460;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  border-top: 2px #3060a0;"
    "  border-left: 2px #3060a0;"
    "  border-bottom: 2px #0a1530;"
    "  border-right: 2px #0a1530;"
    "}"
    ".welcome-btn-primary:hover { background: #24407a; }"
    /* Welcome divider */
    ".welcome-hr {"
    "  width: 100%;"
    "  height: 1px;"
    "  background: #1c1c28;"
    "  margin: 0px 0px 20px 0px;"
    "  flex-shrink: 0;"
    "}"
    ".welcome-cols {"
    "  flex-direction: row;"
    "  gap: 48px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  flex-wrap: wrap;"
    "}"
    ".welcome-col {"
    "  flex-direction: column;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  flex-shrink: 0;"
    "}"
    /* ===== Plugin Manager ===== */
    ".pm-root {"
    "  background: #18181e;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".pm-body {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* Left: plugin list panel */
    ".pm-left {"
    "  background: #12121a;"
    "  width: 260px;"
    "  height: 100%;"
    "  min-height: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-right: 2px #070709;"
    "  overflow: hidden;"
    "}"
    ".pm-search-row {"
    "  background: #1a1a22;"
    "  width: 100%;"
    "  height: 40px;"
    "  padding: 6px 8px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  border-top: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  overflow: hidden;"
    "}"
    /* Search input — inset */
    ".pm-search-input {"
    "  background: #0e0e12;"
    "  border-color: #0e0e12;"
    "  border-width: 0px;"
    "  corner-radius: 0px;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "  border-right: 2px #3c3c48;"
    "}"
    ".pm-list {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    ".pm-item {"
    "  background: transparent;"
    "  width: 100%;"
    "  min-height: 54px;"
    "  padding: 8px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-bottom: 1px #0c0c10;"
    "  corner-radius: 0px;"
    "}"
    ".pm-item:hover { background: #1c1c26; }"
    ".pm-item-selected {"
    "  background: #182e50;"
    "  border-left: 3px #3d6d9a;"
    "}"
    ".pm-item-selected:hover { background: #1e3860; }"
    ".pm-item-name {"
    "  color: #b8b8c4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "}"
    ".pm-item-version {"
    "  color: #404058;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  padding: 2px 0px 0px 0px;"
    "}"
    ".pm-item-disabled-name {"
    "  color: #505060;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "}"
    ".pm-item-disabled-version {"
    "  color: #2e2e3a;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  padding: 2px 0px 0px 0px;"
    "}"
    /* Right: plugin detail */
    ".pm-right {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 20px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".pm-empty {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: center;"
    "  align-items: center;"
    "}"
    ".pm-empty-text {"
    "  color: #2a2a3a;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "}"
    ".pm-detail-name {"
    "  color: #c8c8d4;"
    "  font-size: 16px;"
    "  text-wrap: nowrap;"
    "  padding: 0px 0px 6px 0px;"
    "}"
    ".pm-badge-row {"
    "  gap: 6px;"
    "  padding: 0px 0px 12px 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".pm-badge {"
    "  height: 18px;"
    "  padding: 0px 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  border-top: 1px #4c4c58;"
    "  border-left: 1px #4c4c58;"
    "  border-bottom: 1px #070709;"
    "  border-right: 1px #070709;"
    "}"
    ".pm-badge-enabled  { background: #103020; }"
    ".pm-badge-disabled { background: #301010; }"
    ".pm-badge-static   { background: #102030; }"
    ".pm-badge-dynamic  { background: #201030; }"
    ".pm-badge-text { font-size: 10px; text-wrap: nowrap; }"
    ".pm-badge-text-enabled  { color: #40a060; }"
    ".pm-badge-text-disabled { color: #a04040; }"
    ".pm-badge-text-static   { color: #4878a8; }"
    ".pm-badge-text-dynamic  { color: #7848a8; }"
    /* Action buttons row */
    ".pm-action-row {"
    "  gap: 8px;"
    "  padding: 0px 0px 14px 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    /* Generic plugin action button — raised */
    ".pm-btn {"
    "  background: #262636;"
    "  height: 28px;"
    "  padding: 0px 14px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  border-top: 2px #4c4c58;"
    "  border-left: 2px #4c4c58;"
    "  border-bottom: 2px #070709;"
    "  border-right: 2px #070709;"
    "}"
    ".pm-btn:hover { background: #303048; }"
    ".pm-btn-text {"
    "  color: #8888a0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".pm-btn-enable {"
    "  background: #0e2818;"
    "  border-top: 2px #204818;"
    "  border-left: 2px #204818;"
    "  border-bottom: 2px #040e08;"
    "  border-right: 2px #040e08;"
    "}"
    ".pm-btn-enable:hover { background: #142e1e; }"
    ".pm-btn-enable-text { color: #4aaa68; }"
    ".pm-btn-disable {"
    "  background: #281010;"
    "  border-top: 2px #481010;"
    "  border-left: 2px #481010;"
    "  border-bottom: 2px #0a0404;"
    "  border-right: 2px #0a0404;"
    "}"
    ".pm-btn-disable:hover { background: #301414; }"
    ".pm-btn-disable-text { color: #aa4a4a; }"
    /* Detail section divider */
    ".pm-hr {"
    "  height: 1px;"
    "  background: #1a1a28;"
    "  margin: 0px 0px 12px 0px;"
    "  flex-shrink: 0;"
    "}"
    /* Key-value info rows */
    ".pm-info-row {"
    "  gap: 0px;"
    "  height: 22px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".pm-info-key {"
    "  color: #383848;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 80px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".pm-info-value {"
    "  color: #6e7090;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "  text-wrap: nowrap;"
    "}"

    /* ===== Settings Window ===== */

    ".sw-root {"
    "  background: #18181e;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".sw-body {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* Left nav panel */
    ".sw-left {"
    "  background: #12121a;"
    "  width: 180px;"
    "  height: 100%;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 8px 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-right: 2px #070709;"
    "  overflow: hidden;"
    "}"
    /* Nav tab buttons */
    ".sw-tab-btn {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 36px;"
    "  padding: 0px 16px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  corner-radius: 0px;"
    "  gap: 0px;"
    "}"
    ".sw-tab-btn:hover { background: #1e1e28; }"
    ".sw-tab-btn-active {"
    "  background: #182e50;"
    "  border-left: 3px #3d6d9a;"
    "}"
    ".sw-tab-btn-active:hover { background: #1e3860; }"
    ".sw-tab-label {"
    "  color: #585868;"
    "  font-size: 13px;"
    "  text-wrap: nowrap;"
    "}"
    ".sw-tab-label-active { color: #b8b8cc; }"
    /* Right content panel */
    ".sw-right {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 24px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".sw-section-title {"
    "  color: #c0c0cc;"
    "  font-size: 15px;"
    "  text-wrap: nowrap;"
    "  margin-bottom: 8px;"
    "}"
    ".sw-hr {"
    "  height: 1px;"
    "  background: #1c1c28;"
    "  margin: 0px 0px 16px 0px;"
    "  flex-shrink: 0;"
    "}"
    ".sw-setting-row {"
    "  width: 100%;"
    "  height: 32px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  gap: 12px;"
    "  justify-content: flex-start;"
    "  padding: 0px;"
    "}"
    ".sw-setting-label {"
    "  color: #9090a0;"
    "  font-size: 13px;"
    "  width: 80px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".sw-setting-value {"
    "  color: #4888c0;"
    "  font-size: 13px;"
    "  width: 54px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "  text-align: right;"
    "}"
    /* Scale input — inset well */
    ".sw-scale-input {"
    "  width: 80px;"
    "  height: 26px;"
    "  font-size: 13px;"
    "  corner-radius: 0px;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "  border-right: 2px #3c3c48;"
    "}"
    /* Workspace search window */
    ".search-root-window {"
    "  width: 100%;"
    "  height: 100%;"
    "  background: #101014;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  overflow: hidden;"
    "}"
    ".search-body {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".search-header {"
    "  width: 100%;"
    "  padding: 14px 16px 12px 16px;"
    "  gap: 7px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #1b1b24;"
    "  border-bottom: 1px #343442;"
    "  align-items: stretch;"
    "}"
    ".search-title {"
    "  color: #858598;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "}"
    ".search-input {"
    "  width: 100%;"
    "  height: 32px;"
    "  color: #d0d0dc;"
    "  background: #0c0c10;"
    "  font-size: 14px;"
    "  padding: 0px 10px;"
    "  corner-radius: 0px;"
    "  border-top: 2px #070709;"
    "  border-left: 2px #070709;"
    "  border-bottom: 2px #3c3c48;"
    "  border-right: 2px #3c3c48;"
    "}"
    ".search-root {"
    "  color: #505062;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "}"
    ".search-results {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  gap: 0px;"
    "  padding: 3px 0px;"
    "  background: #111116;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "  align-items: stretch;"
    "}"
    ".search-result {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  height: 30px;"
    "  padding: 0px 10px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: transparent;"
    "  corner-radius: 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".search-result:hover { background: #20202a; }"
    ".search-result-selected {"
    "  background: #18304f;"
    "  border-left: 3px #4c82b0;"
    "}"
    ".search-result-selected:hover { background: #1d3a60; }"
    ".search-result-path {"
    "  color: #b8beca;"
    "  font-size: 13px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "  flex-grow: 1;"
    "  min-width: 0px;"
    "}"
    ".search-result-line {"
    "  color: #5993be;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    ".search-empty {"
    "  color: #565666;"
    "  font-size: 13px;"
    "  padding: 18px 16px;"
    "}"
    ".search-footer {"
    "  width: 100%;"
    "  height: 28px;"
    "  padding: 0px 12px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #1b1b24;"
    "  border-top: 1px #343442;"
    "  align-items: center;"
    "  gap: 12px;"
    "}"
    ".search-progress {"
    "  width: 180px;"
    "  height: 6px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #30303c;"
    "}"
    ".search-status {"
    "  color: #686878;"
    "  font-size: 11px;"
    "  flex-grow: 1;"
    "  text-wrap: nowrap;"
    "}"
    ".search-help {"
    "  color: #505062;"
    "  font-size: 11px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".search-preview {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  background: #0d0d11;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".search-preview-header {"
    "  width: 100%;"
    "  height: 30px;"
    "  padding: 0px 12px;"
    "  background: #191922;"
    "  border-bottom: 1px #30303c;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "}"
    ".search-preview-title {"
    "  color: #aeb6c5;"
    "  font-size: 12px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "}"
    ".search-preview-code {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  padding: 8px 0px;"
    "  gap: 0px;"
    "  overflow: scroll;"
    "  align-items: stretch;"
    "}"
    ".search-preview-row {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  height: 20px;"
    "  padding: 0px 10px 0px 0px;"
    "  gap: 12px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "}"
    ".search-preview-row-match {"
    "  background: #1a3554;"
    "  border-left: 3px #4c82b0;"
    "}"
    ".search-preview-number {"
    "  width: 48px;"
    "  color: #464656;"
    "  font-size: 11px;"
    "  text-align: right;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".search-preview-text {"
    "  color: #a8adb8;"
    "  font-size: 12px;"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    ".search-preview-empty {"
    "  color: #565666;"
    "  font-size: 13px;"
    "  padding: 18px;"
    "}";

#endif /* SOL_UI_STYLE_H */
