// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Sol contributors.

/* style.h — Sol's main-window stylesheet + presentation defaults.
 *
 * Keep style edits in this single header to iterate quickly without
 * touching layout/logic code in the .c modules.
 */

#ifndef SOL_UI_STYLE_H
#define SOL_UI_STYLE_H

#include "sol_ui_constants.h"

/* Window presentation defaults. */
#define SOL_UI_WINDOW_TITLE  "Sol"
#define SOL_UI_WINDOW_WIDTH  1080
#define SOL_UI_WINDOW_HEIGHT 720
#define SOL_UI_DEFAULT_THEME_ID   "com.sol.theme.glass"
#define SOL_UI_DEFAULT_THEME_NAME "Glass"

/* Split bar presentation defaults. */
#define SOL_UI_SPLIT_BAR_SIZE        SOL_UI_PANEL_GAP_PX

/* ------------------------------------------------------------------
 * Minimal glass theme for Sol.
 *
 * The animated canvas is intentionally unobstructed through the editor.
 * Navigation and chrome use cool translucent surfaces over localized blur,
 * tonal separation, compact spacing, and restrained blue accents.
 * ------------------------------------------------------------------ */
static const char *SOL_UI_DEFAULT_THEME_CSS =
    "* {"
    "  scrollbar-width: 8px; scrollbar-radius: 0px;"
    "  scrollbar-track-color: rgba(4, 7, 11, 0.30);"
    "  scrollbar-thumb-color: rgba(126, 145, 168, 0.38);"
    "  scrollbar-thumb-active-color: rgba(154, 180, 210, 0.62);"
    "}"
    "splitter { background: transparent; color: rgba(89, 122, 163, 0.18); }"
    /* ===== Causality system chrome ===== */
    ".ca-titlebar {"
    "  background: rgba(4, 8, 15, 0.90); "
    "}"
    ".ca-titlebar-menu { height: 100%; align-items: center; background: transparent; }"
    ".ca-titlebar-menu-item {"
    "  height: 100%; padding: 0px 6px; color: #aeb8c7;"
    "  background: transparent;  border-radius: 0px;"
    "  font-size: 11px;"
    "}"
    ".ca-titlebar-menu-item:hover { background: rgba(117, 151, 193, 0.14); color: #f0f3f7; }"
    ".ca-titlebar-drag { height: 100%; background: transparent; }"
    ".ca-titlebar-title { color: #a7b1c0; font-size: 11px; }"
    ".ca-titlebar-controls { height: 100%; gap: 4px; align-items: center; }"
    ".ca-titlebar-control {"
    "  width: 24px; height: 20px; color: #b4becb; background: transparent;"
    "   border-radius: 0px; font-size: 10px;"
    "}"
    ".ca-titlebar-control:hover { background: rgba(117, 151, 193, 0.12); }"
    ".ca-titlebar-close { color: #ff8b8b; }"
    ".ca-titlebar-close:hover { background: rgba(220, 78, 92, 0.20); }"
    ".ca-popup-root {"
    "  width: 100%; height: 100%; padding: 18px; background: rgba(4, 7, 11, 0.86);"
    "  align-items: stretch; justify-content: center;"
    "}"
    ".ca-popup-card {"
    "  padding: 18px; gap: 12px; background: rgba(10, 15, 23, 0.86);"
    "   border-radius: 0px;"
    "}"
    ".ca-popup-title { color: #e1e6ed; font-size: 13px; }"
    ".ca-popup-message { color: #aab4c2; font-size: 11px; text-wrap: wrap; }"
    ".ca-popup-actions { gap: 8px; justify-content: flex-end; }"
    ".ca-popup-btn {"
    "  padding: 6px 14px; color: #d7e0ea; background: rgba(89, 129, 177, 0.16);"
    "   border-radius: 0px;"
    "}"
    ".ca-popup-btn:hover, .ca-popup-btn-primary:hover { background: rgba(91, 151, 218, 0.25); }"
    ".ca-select-popup, .ca-tooltip, .ca-context-menu, .ca-menubar-popup {"
    "  background: rgb(13, 17, 23); color: #d7e0ea; border-radius: 0px;"
    "}"
    ".ca-overlay-hover { background: rgba(91, 151, 218, 0.18); border-radius: 0px; }"
    ".ca-overlay-selected { background: rgba(75, 137, 205, 0.28); color: #f2f5f8; }"
    ".ca-titlebar-menu-item { color: #aeb8c7; font-size: 11px; }"
    ".ca-titlebar-menu-item:hover { background: rgba(117, 151, 193, 0.14); color: #f0f3f7; }"

    /* ===== Root + workspace shell ===== */
    ".app-root {"
    "  background: transparent;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".bg-host {"
    "  width: 100%;"
    "  height: 100%;"
    "}"
    ".bg-viewport {"
    "  width: 100%;"
    "  height: 100%;"
    "}"
    ".workspace-host {"
    "  background: transparent;"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-full {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-main-content {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".workspace-buffer-area {"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* ===== Left file tree panel ===== */
    ".tree-panel {"
    "  background: rgba(30, 30, 36, 0.82);"
    "  width: 100%;"
    "  height: 100%;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".plugin-side-panel {"
    "  background: rgba(30, 30, 36, 0.82);"
    "  width: 100%;"
    "  height: 100%;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    /* Sticky section header */
    ".tree-section-header {"
    "  background: rgba(36, 36, 48, 0.88);"
    "  width: 100%;"
    "  height: 26px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".tree-section-title {"
    "  color: #5a5a6a;"
    "  font-size: 10px;"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "}"
    /* Scrollable list container */
    ".tree-scroll-area {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 2px 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    ".tree-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0px 6px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "}"
    ".tree-row:hover { background: #262630; }"
    /* Root folder label row */
    ".tree-root-row {"
    "  background: rgba(36, 36, 48, 0.88);"
    "  width: 100%;"
    "  height: 24px;"
    "  padding: 0px 8px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "}"
    /* Indent spacer */
    ".tree-indent {"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    /* Disclosure chevron */
    ".tree-arrow {"
    "  color: #4a4a58;"
    "  font-size: 10px;"
    "  width: 14px;"
    "  flex-shrink: 0;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-arrow-open { color: #6868a0; }"
    /* Icon column */
    ".tree-icon {"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 16px;"
    "  flex-shrink: 0;"
    "  margin-right: 5px;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    ".tree-icon-dir-closed { color: #3d5e9a; }"
    ".tree-icon-dir-open   { color: #5578c0; }"
    ".tree-icon-file       { color: #404050; }"
    ".tree-icon-c          { color: #5a8ab0; }"
    ".tree-icon-h          { color: #a070c0; }"
    ".tree-icon-py         { color: #8aaa60; }"
    ".tree-icon-js         { color: #c8a840; }"
    ".tree-icon-ts         { color: #5a8ab0; }"
    ".tree-icon-json       { color: #b06048; }"
    ".tree-icon-html       { color: #a05838; }"
    ".tree-icon-css        { color: #5a8888; }"
    ".tree-icon-md         { color: #607080; }"
    ".tree-icon-cmake      { color: #907030; }"
    /* Name label */
    ".tree-name {"
    "  color: #9898a4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".tree-name-dir {"
    "  color: #b0b8c8;"
    "}"
    /* ===== Sticky ancestor headers ===== */
    ".tree-sticky-host {"
    "  padding: 0;"
    "  gap: 0;"
    "}"
    ".tree-sticky-row {"
    "  background: rgba(32, 32, 40, 0.90);"
    "  z-index: 5;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0 6px;"
    "  gap: 0;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "}"
    ".tree-sticky-row:hover {"
    "  background: #262630;"
    "}"
    /* ===== Buffer panes ===== */
    ".buffer-pane {"
    "  background: rgba(21, 21, 24, 0.82);"
    "  padding: 3px 0px 0px 0px;"
    "  gap: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".buffer-pane-active {"
    "  background: rgba(24, 24, 30, 0.82);"
    "}"
    /* ===== Tab strip ===== */
    ".buffer-tabs-row {"
    "  width: 100%;"
    "  height: 19px;"
    "  background: rgba(30, 30, 38, 0.82);"
    "  padding: 1px 3px;"
    "  gap: 1px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    /* Inactive tab */
    ".buffer-tab {"
    "  background: rgba(40, 40, 50, 0.82);"
    "  width: 140px;"
    "  height: 17px;"
    "  padding: 0px 2px 0px 7px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "}"
    /* Active tab — depressed/merged look, same bg as buffer body */
    ".buffer-tab-active {"
    "  background: rgba(13, 13, 17, 0.82);"
    "}"
    ".buffer-tab-text {"
    "  color: #585868;"
    "  width: 98px;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "}"
    ".buffer-tab-text-active {"
    "  color: #c8c8d0;"
    "}"
    /* Unsaved-changes dot, shown between the label and the close button. */
    ".buffer-tab-dirty {"
    "  color: #e0a030;"
    "  width: 10px;"
    "  font-size: 8px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "}"
    ".buffer-tab-dirty-active {"
    "  color: #f0b840;"
    "}"
    ".buffer-tab-close {"
    "  background: transparent;"
    "  width: 16px;"
    "  height: 16px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  justify-content: center;"
    "  border-radius: 0px;"
    "  z-index: 1;"
    "}"
    ".buffer-tab-close:hover {"
    "  background: #3a1e1e;"
    "}"
    ".buffer-tab-close-icon {"
    "  color: #3a3a4a;"
    "  font-size: 11px;"
    "}"
    ".buffer-tab-close-icon-active {"
    "  color: #686878;"
    "}"
    /* Text area body — deeply inset "screen" look */
    ".buffer-body {"
    "  background: rgba(13, 13, 17, 0.78);"
    "  padding: 0px;"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    /* Inner row: text column on the left, scrollbar on the right */
    ".buffer-scroll-row {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  gap: 0px;"
    "  padding: 0px;"
    "  overflow: hidden;"
    "}"
    ".buffer-text-col {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 8px;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow-x: hidden;"
    "  overflow-y: hidden;"
    "}"
    /* Left gutter */
    ".buffer-gutter-col {"
    "  width: 56px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 8px 8px 8px 8px;"
    "  gap: 0px;"
    "  background: rgba(10, 10, 13, 0.82);"
    "  overflow: hidden;"
    "  align-items: flex-end;"
    "}"
    ".buffer-gutter-line {"
    "  color: #3a3a48;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  width: 100%;"
    "  padding: 0px 4px 0px 0px;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "}"
    ".buffer-gutter-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-line {"
    "  color: #c4c4cc;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Highlight token classes */
    ".hl-plain   { color: #c4c4cc; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-keyword   { color: #c792ea; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-comment   { color: #546e7a; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-string    { color: #c3e88d; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-number    { color: #f78c6c; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-type      { color: #ffcb6b; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-function  { color: #82aaff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-property  { color: #89ddff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-macro     { color: #ffb62c; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-tag       { color: #f07178; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-attribute { color: #bb80b3; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-regex     { color: #ff5370; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-escape    { color: #ff9d57; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-namespace { color: #b2ccd6; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-label       { color: #c17e70; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-parameter   { color: #b8d0e8; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-constant    { color: #edc58a; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-operator    { color: #89ddff; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-constructor { color: #82d7c0; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-1 { color: #ffd166; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-2 { color: #ef7aa8; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-3 { color: #72c7f0; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-4 { color: #a7df78; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-5 { color: #c59af0; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".hl-bracket-6 { color: #ff9f68; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; height: 20px; flex-shrink: 0; }"
    ".buffer-line-empty {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "}"
    /* Per-line row */
    ".buffer-line-row {"
    "  height: 20px;"
    "  width: 100%;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow: hidden;"
    "}"
    ".buffer-line-content {"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  overflow: visible;"
    "}"
    /* Selection highlight */
    ".buffer-selection {"
    "  height: 20px;"
    "  background: #182e50;"
    "}"
    ".buffer-column-ruler { background: rgba(150, 165, 185, 0.22); }"
    ".buffer-caret { background: #ffffff; }"
    ".buffer-caret-hidden { opacity: 0; }"
    /* Transparent button wrapping each visible line */
    ".buffer-line-btn {"
    "  width: 100%;"
    "  height: 20px;"
    "  flex-shrink: 0;"
    "  background: rgba(0, 0, 0, 0);"
    "  padding: 0px;"
    "  gap: 0px;"
    "}"
    /* ===== Custom vertical scrollbar (retro chunky style) ===== */
    ".buffer-scrollbar {"
    "  width: 14px;"
    "  height: 100%;"
    "  background: rgba(12, 12, 15, 0.82);"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "}"
    ".buffer-scrollbar-spacer {"
    "  width: 14px;"
    "  flex-shrink: 0;"
    "}"
    /* Raised scrollbar thumb */
    ".buffer-scrollbar-thumb {"
    "  width: 14px;"
    "  background: #2e2e38;"
    "  border-radius: 0px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-scrollbar-thumb-active {"
    "  background: #3a3a46;"
    "}"
    ".buffer-hscrollbar {"
    "  background: rgba(12, 12, 15, 0.82);"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  z-index: 3;"
    "}"
    ".buffer-hscrollbar-spacer {"
    "  height: 14px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-hscrollbar-thumb {"
    "  height: 14px;"
    "  background: #2e2e38;"
    "  border-radius: 0px;"
    "  flex-shrink: 0;"
    "}"
    ".buffer-hscrollbar-thumb-active {"
    "  background: #3a3a46;"
    "}"
    ".buffer-body-text {"
    "  color: #c4c4cc;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    /* ===== Command Flow popup ===== */
    ".cf-overlay {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px " SOL_UI_PANEL_MARGIN_PX_CSS " " SOL_UI_PANEL_MARGIN_PX_CSS " 0px;"
    "  gap: 0px;"
    "  justify-content: flex-end;"
    "  align-items: flex-end;"
    "  overflow: hidden;"
    "}"
    ".cf-panel {"
    "  background: rgba(4, 8, 14, 0.94);"
    "  padding: 6px 6px;"
    "  gap: 2px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".cf-row {"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 2px 6px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".cf-row-error { background: #1c1018; }"
    /* Key badge */
    ".cf-row-key {"
    "  background: rgba(100, 142, 192, 0.16);"
    "  width: 28px;"
    "  height: 18px;"
    "  padding: 0px 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".cf-row-key-text {"
    "  color: #8fc0f2;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "  width: 100%;"
    "}"
    ".cf-row-label {"
    "  color: #c3ccd8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".cf-row-label-error { color: #b06878; }"
    ".cf-row-more {"
    "  color: #738094;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: right;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".cf-empty {"
    "  color: #404050;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 4px 6px;"
    "}"
    /* ===== File picker ===== */
    ".fp-root {"
    "  background: rgba(20, 20, 26, 0.88);"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".fp-host {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    /* Toolbar */
    ".fp-toolbar {"
    "  background: #22222c;"
    "  width: 100%;"
    "  height: 32px;"
    "  padding: 0px 4px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    /* Up / parent button */
    ".fp-up-btn {"
    "  background: #282832;"
    "  width: 26px;"
    "  height: 26px;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "  margin-right: 4px;"
    "}"
    ".fp-up-btn:hover { background: #323244; }"
    ".fp-up-btn-active {"
    "  background: #1c1c24;"
    "}"
    ".fp-up-icon {"
    "  color: #545468;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "}"
    ".fp-up-icon-active { color: #5a98c0; }"
    /* Breadcrumb */
    ".fp-breadcrumb {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "  overflow-x: hidden;"
    "  overflow-y: hidden;"
    "}"
    ".fp-crumb-btn {"
    "  background: transparent;"
    "  height: 24px;"
    "  padding: 0px 5px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "}"
    ".fp-crumb-btn:hover { background: #262630; }"
    ".fp-crumb-btn-active { background: transparent; }"
    ".fp-crumb-text {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-crumb-text-active {"
    "  color: #9898a8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-crumb-sep {"
    "  color: #30303e;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 12px;"
    "  flex-shrink: 0;"
    "  text-align: center;"
    "  text-wrap: nowrap;"
    "}"
    /* Scrollable file list — inset well */
    ".fp-list {"
    "  background: #101014;"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  padding: 2px 0px;"
    "  gap: 0px;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    /* File / directory rows */
    ".fp-row {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "}"
    ".fp-row:hover { background: #20202a; }"
    ".fp-row-name {"
    "  color: #9898a8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".fp-row-name-dir { color: #a8b0c4; }"
    ".fp-empty {"
    "  color: #383848;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  padding: 14px 16px;"
    "}"
    /* Footer */
    ".fp-footer {"
    "  background: #22222c;"
    "  width: 100%;"
    "  height: 46px;"
    "  padding: 0px 12px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    /* Cancel button */
    ".fp-action-cancel {"
    "  background: #28283a;"
    "  height: 28px;"
    "  padding: 0px 16px;"
    "  border-radius: 0px;"
    "  color: #a8a8b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  align-self: center;"
    "}"
    ".fp-action-cancel:hover { background: #323248; }"
    /* Primary action button */
    ".fp-action-primary {"
    "  background: #1c3460;"
    "  height: 28px;"
    "  padding: 0px 16px;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  align-self: center;"
    "}"
    ".fp-action-primary:hover { background: #24407a; }"
    /* Toolbar group spacing */
    ".fp-toolbar-sep {"
    "  width: 1px;"
    "  height: 16px;"
    "  background: #0e0e14;"
    "  flex-shrink: 0;"
    "  margin-right: 3px;"
    "  margin-left: 3px;"
    "}"
    /* Inline new-folder creation bar */
    ".fp-new-folder-bar {"
    "  background: #1e1e28;"
    "  width: 100%;"
    "  height: 36px;"
    "  padding: 0px 10px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".fp-new-folder-label {"
    "  color: #666678;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Folder name text input — inset */
    ".fp-new-folder-input {"
    "  flex-grow: 1;"
    "  min-width: 80px;"
    "  height: 24px;"
    "  color: #b8c8e0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  background: #0c0c10;"
    "  border-radius: 0px;"
    "  padding: 0px 8px;"
    "}"
    /* Small create/cancel buttons inside the new-folder bar */
    ".fp-nf-create {"
    "  background: #1c3460;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "}"
    ".fp-nf-create:hover { background: #24407a; }"
    ".fp-nf-cancel {"
    "  background: #28283a;"
    "  height: 24px;"
    "  padding: 0px 12px;"
    "  border-radius: 0px;"
    "  color: #a8a8b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "}"
    ".fp-nf-cancel:hover { background: #323248; }"
    /* Footer left info text */
    ".fp-footer-count {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    /* Spacer */
    ".fp-footer-spacer {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "}"
    /* New Folder button in footer */
    ".fp-action-new-folder {"
    "  background: #22222e;"
    "  height: 28px;"
    "  padding: 0px 10px;"
    "  border-radius: 0px;"
    "  color: #505060;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "}"
    ".fp-action-new-folder:hover { background: #2c2c3e; color: #6868a0; }"
    ".fp-action-new-folder-active {"
    "  background: #1a1a26;"
    "  color: #5a90c0;"
    "}"
    /* Sortable column header */
    ".fp-colhdr {"
    "  background: #1a1a22;"
    "  width: 100%;"
    "  height: 22px;"
    "  padding: 0px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".fp-colhdr-icon-gap {"
    "  width: 21px;"
    "  flex-shrink: 0;"
    "}"
    ".fp-colhdr-name-cell {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-size-cell {"
    "  width: 72px;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-date-cell {"
    "  width: 112px;"
    "  flex-shrink: 0;"
    "  align-items: stretch;"
    "}"
    ".fp-colhdr-btn {"
    "  width: 100%;"
    "  height: 22px;"
    "  background: transparent;"
    "  padding: 0px 4px;"
    "  gap: 4px;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "}"
    ".fp-colhdr-btn:hover { background: #222232; }"
    ".fp-colhdr-btn-active { background: transparent; }"
    ".fp-colhdr-btn-end {"
    "  width: 100%;"
    "  height: 22px;"
    "  background: transparent;"
    "  padding: 0px 4px;"
    "  gap: 4px;"
    "  justify-content: flex-end;"
    "  align-items: center;"
    "}"
    ".fp-colhdr-btn-end:hover { background: #222232; }"
    ".fp-colhdr-text {"
    "  color: #484858;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".fp-colhdr-text-active { color: #7898b8; }"
    ".fp-colhdr-sort-arrow {"
    "  color: #7898b8;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    /* Per-row metadata columns */
    ".fp-row-size {"
    "  color: #3e3e50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 72px;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "}"
    ".fp-row-date {"
    "  color: #3e3e50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 112px;"
    "  flex-shrink: 0;"
    "  text-align: right;"
    "  text-wrap: nowrap;"
    "  padding-right: 4px;"
    "}"
    /* ===== Status bar ===== */
    ".status-bar {"
    "  background: rgba(17, 17, 24, 0.88);"
    "  width: 100%;"
    "  height: 22px;"
    "  box-sizing: border-box;"
    "  padding: 0px 8px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".status-bar-left {"
    "  width: auto;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  gap: 6px;"
    "  min-width: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".status-bar-right {"
    "  width: auto; gap: 8px; justify-content: flex-end; align-items: center;"
    "  min-width: 0px; flex-grow: 0; flex-shrink: 1; overflow: hidden;"
    "}"
    ".status-plugin-segment, .status-plugin {"
    "  width: auto; padding: 0px 2px; color: #98a5b7; font-size: 10px;"
    "  text-wrap: nowrap; flex-grow: 0; flex-shrink: 0; align-items: center;"
    "}"
    ".status-bar-warning {"
    "  width: auto; padding: 0px 6px; color: #e0a030; font-size: 10px;"
    "  text-wrap: nowrap; overflow: hidden;"
    "  max-width: 420px; flex-grow: 0; flex-shrink: 1; align-items: center;"
    "}"
    ".status-bar-value {"
    "  width: auto;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge {"
    "  width: 14px;"
    "  height: 14px;"
    "  justify-content: center;"
    "  align-items: center;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  overflow: hidden;"
    "}"
    ".status-bar-badge-key     { background: #163254; }"
    ".status-bar-badge-command { background: #1c3c30; }"
    ".status-bar-badge-leader  { background: #3e3010; }"
    ".status-bar-badge-text {"
    "  color: #b0c8e0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    ".status-bar-text {"
    "  color: #787898;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: left;"
    "  width: auto;"
    "  flex-grow: 0;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "}"
    /* ===== Welcome screen ===== */
    ".welcome-pane {"
    "  background: rgba(20, 20, 26, 0.78);"
    "  width: 100%;"
    "  height: 100%;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 48px 64px;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  overflow: hidden;"
    "}"
    ".welcome-title {"
    "  color: #c0c0cc;"
    "  font-size: 22px;"
    "  text-wrap: nowrap;"
    "}"
    ".welcome-subtitle {"
    "  color: #404050;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  padding: 4px 0px 28px 0px;"
    "}"
    ".welcome-section {"
    "  width: auto;"
    "  gap: 2px;"
    "  padding: 0px 0px 20px 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-section-label {"
    "  color: #3c3c50;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  padding: 0px 0px 6px 0px;"
    "}"
    ".welcome-row {"
    "  width: auto;"
    "  height: 20px;"
    "  gap: 12px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-key {"
    "  color: #4888c0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  width: 112px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    ".welcome-desc {"
    "  color: #70708c;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "}"
    /* Welcome action buttons */
    ".welcome-actions {"
    "  flex-direction: row;"
    "  gap: 8px;"
    "  padding: 0px 0px 20px 0px;"
    "  flex-wrap: wrap;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".welcome-btn {"
    "  padding: 6px 16px;"
    "  background: #26263a;"
    "  border-radius: 0px;"
    "  color: #a0a0b4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "}"
    ".welcome-btn:hover { background: #303050; }"
    ".welcome-btn-primary {"
    "  padding: 6px 16px;"
    "  background: #1c3460;"
    "  border-radius: 0px;"
    "  color: #b8ccec;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-shrink: 0;"
    "}"
    ".welcome-btn-primary:hover { background: #24407a; }"
    /* Welcome divider */
    ".welcome-hr {"
    "  width: 100%;"
    "  height: 1px;"
    "  background: #1c1c28;"
    "  margin: 0px 0px 20px 0px;"
    "  flex-shrink: 0;"
    "}"
    ".welcome-cols {"
    "  flex-direction: row;"
    "  gap: 48px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  flex-wrap: wrap;"
    "}"
    ".welcome-col {"
    "  flex-direction: column;"
    "  gap: 0px;"
    "  align-items: flex-start;"
    "  justify-content: flex-start;"
    "  flex-shrink: 0;"
    "}"
    /* ===== Plugin Manager ===== */
    ".pm-root {"
    "  background: #18181e;"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".pm-body {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* Left: plugin list panel */
    ".pm-left {"
    "  background: #12121a;"
    "  width: 260px;"
    "  height: 100%;"
    "  min-height: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".pm-search-row {"
    "  background: #1a1a22;"
    "  width: 100%;"
    "  height: 40px;"
    "  padding: 6px 8px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    /* Search input — inset */
    ".pm-search-input {"
    "  background: #0e0e12;"
    "  border-radius: 0px;"
    "}"
    ".pm-list {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "}"
    ".pm-item {"
    "  background: transparent;"
    "  width: 100%;"
    "  min-height: 54px;"
    "  padding: 8px 12px;"
    "  gap: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  border-radius: 0px;"
    "}"
    ".pm-item:hover { background: #1c1c26; }"
    ".pm-item-selected {"
    "  background: #182e50;"
    "}"
    ".pm-item-selected:hover { background: #1e3860; }"
    ".pm-item-name {"
    "  color: #b8b8c4;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "}"
    ".pm-item-version {"
    "  color: #404058;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  padding: 2px 0px 0px 0px;"
    "}"
    ".pm-item-disabled-name {"
    "  color: #505060;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "}"
    ".pm-item-disabled-version {"
    "  color: #2e2e3a;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "  text-align: left;"
    "  padding: 2px 0px 0px 0px;"
    "}"
    /* Right: plugin detail */
    ".pm-right {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 20px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".pm-empty {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  justify-content: center;"
    "  align-items: center;"
    "}"
    ".pm-empty-text {"
    "  color: #2a2a3a;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-align: center;"
    "}"
    ".pm-detail-name {"
    "  color: #c8c8d4;"
    "  font-size: 16px;"
    "  text-wrap: nowrap;"
    "  padding: 0px 0px 6px 0px;"
    "}"
    ".pm-badge-row {"
    "  gap: 6px;"
    "  padding: 0px 0px 12px 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".pm-badge {"
    "  height: 18px;"
    "  padding: 0px 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "}"
    ".pm-badge-enabled  { background: #103020; }"
    ".pm-badge-disabled { background: #301010; }"
    ".pm-badge-static   { background: #102030; }"
    ".pm-badge-dynamic  { background: #201030; }"
    ".pm-badge-text { font-size: 10px; text-wrap: nowrap; }"
    ".pm-badge-text-enabled  { color: #40a060; }"
    ".pm-badge-text-disabled { color: #a04040; }"
    ".pm-badge-text-static   { color: #4878a8; }"
    ".pm-badge-text-dynamic  { color: #7848a8; }"
    /* Action buttons row */
    ".pm-action-row {"
    "  gap: 8px;"
    "  padding: 0px 0px 14px 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    /* Generic plugin action button */
    ".pm-btn {"
    "  background: #262636;"
    "  height: 28px;"
    "  padding: 0px 14px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: center;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "}"
    ".pm-btn:hover { background: #303048; }"
    ".pm-btn-text {"
    "  color: #8888a0;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap;"
    "}"
    ".pm-btn-enable {"
    "  background: #0e2818;"
    "}"
    ".pm-btn-enable:hover { background: #142e1e; }"
    ".pm-btn-enable-text { color: #4aaa68; }"
    ".pm-btn-disable {"
    "  background: #281010;"
    "}"
    ".pm-btn-disable:hover { background: #301414; }"
    ".pm-btn-disable-text { color: #aa4a4a; }"
    /* Detail section divider */
    ".pm-hr {"
    "  height: 1px;"
    "  background: #1a1a28;"
    "  margin: 0px 0px 12px 0px;"
    "  flex-shrink: 0;"
    "}"
    /* Key-value info rows */
    ".pm-info-row {"
    "  gap: 0px;"
    "  height: 22px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".pm-info-key {"
    "  color: #383848;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  width: 80px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".pm-info-value {"
    "  color: #6e7090;"
    "  font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  overflow: hidden;"
    "  text-wrap: nowrap;"
    "}"

    /* ===== Settings Window ===== */

    ".sw-root {"
    "  background: rgba(24, 24, 30, 0.88);"
    "  width: 100%;"
    "  height: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".sw-body {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  width: 100%;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* Left nav panel */
    ".sw-left {"
    "  background: #12121a;"
    "  width: 180px;"
    "  height: 100%;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 8px 0px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    /* Nav tab buttons */
    ".sw-tab-btn {"
    "  background: transparent;"
    "  width: 100%;"
    "  height: 36px;"
    "  padding: 0px 16px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  justify-content: flex-start;"
    "  align-items: center;"
    "  border-radius: 0px;"
    "  gap: 0px;"
    "}"
    ".sw-tab-btn:hover { background: #1e1e28; }"
    ".sw-tab-btn-active {"
    "  background: #182e50;"
    "}"
    ".sw-tab-btn-active:hover { background: #1e3860; }"
    ".sw-tab-label {"
    "  color: #585868;"
    "  font-size: 13px;"
    "  text-wrap: nowrap;"
    "}"
    ".sw-tab-label-active { color: #b8b8cc; }"
    /* Right content panel */
    ".sw-right {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  padding: 24px;"
    "  gap: 0px;"
    "  justify-content: flex-start;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".sw-section-title {"
    "  color: #c0c0cc;"
    "  font-size: 15px;"
    "  text-wrap: nowrap;"
    "  margin-bottom: 8px;"
    "}"
    ".sw-hr {"
    "  height: 1px;"
    "  background: #1c1c28;"
    "  margin: 0px 0px 16px 0px;"
    "  flex-shrink: 0;"
    "}"
    ".sw-setting-row {"
    "  width: 100%;"
    "  height: 32px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  gap: 12px;"
    "  justify-content: flex-start;"
    "  padding: 0px;"
    "}"
    ".sw-setting-label {"
    "  color: #9090a0;"
    "  font-size: 13px;"
    "  width: 80px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".sw-setting-value {"
    "  color: #4888c0;"
    "  font-size: 13px;"
    "  width: 54px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "  text-align: right;"
    "}"
    /* Scale input — inset well */
    ".sw-scale-input {"
    "  width: 80px;"
    "  height: 26px;"
    "  font-size: 13px;"
    "  border-radius: 0px;"
    "}"
    /* Appearance sliders — fill remaining row width */
    ".sw-slider {"
    "  flex-grow: 1;"
    "  height: 20px;"
    "}"
    ".sw-select {"
    "  width: 200px;"
    "  height: 28px;"
    "  font-size: 13px;"
    "  border-radius: 0px;"
    "  padding: 0px 8px;"
    "}"
    ".sw-setting-group {"
    "  width: 100%;"
    "  padding: 8px 0px 0px 0px;"
    "  gap: 8px;"
    "  flex-shrink: 0;"
    "}"
    /* Workspace search window */
    ".search-root-window {"
    "  width: 100%;"
    "  height: 100%;"
    "  background: rgba(16, 16, 20, 0.88);"
    "  padding: 0px;"
    "  gap: 0px;"
    "  overflow: hidden;"
    "}"
    ".search-body {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".search-header {"
    "  width: 100%;"
    "  padding: 14px 16px 12px 16px;"
    "  gap: 7px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #1b1b24;"
    "  align-items: stretch;"
    "}"
    ".search-title {"
    "  color: #858598;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "}"
    ".search-input {"
    "  width: 100%;"
    "  height: 32px;"
    "  color: #d0d0dc;"
    "  background: #0c0c10;"
    "  font-size: 14px;"
    "  padding: 0px 10px;"
    "  border-radius: 0px;"
    "}"
    ".search-root {"
    "  color: #505062;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "}"
    ".search-results {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  gap: 0px;"
    "  padding: 3px 0px;"
    "  background: #111116;"
    "  overflow-y: scroll;"
    "  overflow-x: hidden;"
    "  align-items: stretch;"
    "}"
    ".search-result {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  height: 30px;"
    "  padding: 0px 10px;"
    "  gap: 8px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: transparent;"
    "  border-radius: 0px;"
    "  align-items: center;"
    "  justify-content: flex-start;"
    "}"
    ".search-result:hover { background: #20202a; }"
    ".search-result-selected {"
    "  background: #18304f;"
    "}"
    ".search-result-selected:hover { background: #1d3a60; }"
    ".search-result-path {"
    "  color: #b8beca;"
    "  font-size: 13px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "  flex-grow: 1;"
    "  min-width: 0px;"
    "}"
    ".search-result-line {"
    "  color: #5993be;"
    "  font-size: 11px;"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    ".search-empty {"
    "  color: #565666;"
    "  font-size: 13px;"
    "  padding: 18px 16px;"
    "}"
    ".search-footer {"
    "  width: 100%;"
    "  height: 28px;"
    "  padding: 0px 12px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #1b1b24;"
    "  align-items: center;"
    "  gap: 12px;"
    "}"
    ".search-progress {"
    "  width: 180px;"
    "  height: 6px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  background: #30303c;"
    "  color: #62a6d8;"
    "}"
    ".search-status {"
    "  color: #686878;"
    "  font-size: 11px;"
    "  flex-grow: 1;"
    "  text-wrap: nowrap;"
    "}"
    ".search-help {"
    "  color: #505062;"
    "  font-size: 11px;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".search-preview {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  background: #0d0d11;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".search-preview-header {"
    "  width: 100%;"
    "  height: 30px;"
    "  padding: 0px 12px;"
    "  background: #191922;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "}"
    ".search-preview-title {"
    "  color: #aeb6c5;"
    "  font-size: 12px;"
    "  text-wrap: nowrap;"
    "  overflow: hidden;"
    "}"
    ".search-preview-code {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  padding: 8px 0px;"
    "  gap: 0px;"
    "  overflow: scroll;"
    "  align-items: stretch;"
    "}"
    ".search-preview-row {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  height: 20px;"
    "  padding: 0px 10px 0px 0px;"
    "  gap: 12px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "}"
    ".search-preview-row-match {"
    "  background: #1a3554;"
    "}"
    ".search-preview-number {"
    "  width: 48px;"
    "  color: #464656;"
    "  font-size: 11px;"
    "  text-align: right;"
    "  flex-shrink: 0;"
    "  text-wrap: nowrap;"
    "}"
    ".search-preview-text {"
    "  color: #a8adb8;"
    "  font-size: 12px;"
    "  text-wrap: nowrap;"
    "  flex-shrink: 0;"
    "}"
    ".search-preview-empty {"
    "  color: #565666;"
    "  font-size: 13px;"
    "  padding: 18px;"
    "}"

    /* ===== Terminal panel ===== */
    ".term-panel {"
    "  width: 100%;"
    "  height: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  background: #0e0e10;"
    "  padding: 3px 0px 0px 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".term-header {"
    "  width: 100%;"
    "  height: 19px;"
    "  background: rgba(30, 30, 38, 0.82);"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  padding: 0px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".term-tab {"
    "  height: 17px;"
    "  padding: 0px 2px 0px 7px;"
    "  background: rgba(40, 40, 50, 0.82);"
    "  color: #747480;"
    "  font-size: 12px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  gap: 4px;"
    "  text-wrap: nowrap;"
    "}"
    ".term-tab-active {"
    "  height: 17px;"
    "  padding: 0px 2px 0px 7px;"
    "  background: rgba(13, 13, 17, 0.82);"
    "  color: #c8c8cc;"
    "  font-size: 12px;"
    "  flex-shrink: 0;"
    "  align-items: center;"
    "  gap: 4px;"
    "  text-wrap: nowrap;"
    "}"
    ".term-tab-text {"
    "  font-size: 12px;"
    "  color: #747480;"
    "  text-wrap: nowrap;"
    "}"
    ".term-tab-text-active {"
    "  font-size: 12px;"
    "  color: #c8c8cc;"
    "  text-wrap: nowrap;"
    "}"
    ".term-tab-close {"
    "  width: 16px;"
    "  height: 16px;"
    "  align-items: center;"
    "  justify-content: center;"
    "  border-radius: 2px;"
    "  flex-shrink: 0;"
    "}"
    ".term-tab-close:hover {"
    "  background: #3d3d4a;"
    "}"
    ".term-tab-close-icon {"
    "  font-size: 11px;"
    "  color: #747480;"
    "}"
    ".term-tab-close-icon-active {"
    "  font-size: 11px;"
    "  color: #c8c8cc;"
    "}"
    ".term-viewport {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  min-height: 0px;"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  background: #0e0e10;"
    "  padding: 4px 6px;"
    "  gap: 0px;"
    "  align-items: stretch;"
    "  overflow: hidden;"
    "}"
    ".term-line {"
    "  width: 100%;"
    "  min-width: 0px;"
    "  flex-grow: 0;"
    "  flex-shrink: 0;"
    "  gap: 0px;"
    "  align-items: center;"
    "  overflow: hidden;"
    "}"
    ".term-cell {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  text-wrap: nowrap;"
    "}"
    ".term-cell-bold {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  font-weight: bold;"
    "  text-wrap: nowrap;"
    "}"
    ".term-cell-italic {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  font-style: italic;"
    "  text-wrap: nowrap;"
    "}"
    ".term-cell-bold-italic {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  font-weight: bold;"
    "  font-style: italic;"
    "  text-wrap: nowrap;"
    "}"
    ".term-cursor-focused {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  text-wrap: nowrap;"
    "  background: #c8c8cc;"
    "  color: #0e0e10;"
    "}"
    ".term-cursor-unfocused {"
    "  font-size: 13px;"
    "  font-family: monospace;"
    "  text-wrap: nowrap;"
    "}"
    ".term-filler {"
    "  flex-grow: 1;"
    "  flex-shrink: 1;"
    "  min-height: 0px;"
    "  background: #0e0e10;"
    "}"
    /* ===== Source control plugin =====
       Sized against the app's shared conventions rather than an
       independent scale: primary text at SOL_UI_BOOT_FONT_SIZE_PX_CSS
       (12px, same as .tree-name / .pm-btn-text), secondary/meta text at
       11px (matching .search-result-line), and 16px icon-only buttons
       (matching .buffer-tab-close) instead of an ad-hoc 22px grid. */
    ".scm-header {"
    "  width: 100%; height: 34px; padding: 0px 6px 0px 10px; gap: 7px;"
    "  flex-shrink: 0; align-items: center; background: #242430;"
    "}"
    ".scm-title-icon { color: #6c6c7c; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; }"
    ".scm-title {"
    "  color: #c4c4d2; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; font-weight: 600;"
    "  flex-grow: 1; text-wrap: nowrap;"
    "}"
    /* Icon-only action buttons. Deliberately identical, single size for
       every icon button in this panel — 16px box / 11px glyph — because
       that is the ONE icon-button geometry already proven not to clip
       anywhere in this app (.buffer-tab-close uses these exact numbers).
       Earlier revisions tried a second, larger 20px/12px size for
       header/remote actions and that size clipped the refresh glyph.
       Rather than keep guessing at new numbers, every .scm-* icon button
       now reuses the one combination with a working track record. */
    ".scm-icon-action, .scm-header-icon-action, .scm-action-icon {"
    "  width: 16px; height: 16px; padding: 0px; background: transparent;"
    "  color: #9494a4; border-radius: 0px; justify-content: center;"
    "  align-items: center; flex-shrink: 0;"
    "}"
    ".scm-icon-action:hover, .scm-header-icon-action:hover,"
    ".scm-action-icon:hover { background: #393946; color: #e4e4ec; }"
    ".scm-icon-glyph { font-size: 11px; }"
    ".scm-icon-danger { color: #b97676; }"
    ".scm-icon-danger:hover { background: #542a32; color: #ffb0b0; }"
    ".scm-header-action, .scm-action, .scm-section-action,"
    ".scm-primary-action, .scm-danger-action {"
    "  height: 24px; padding: 0px 9px; background: #2a2a34; color: #b8b8c4;"
    "  border-radius: 0px; font-size: 11px;"
    "}"
    ".scm-header-action:hover, .scm-action:hover,"
    ".scm-section-action:hover { background: #393946; color: #e0e0e8; }"
    ".scm-primary-action { background: #28507a; color: #e8f2ff;  }"
    ".scm-primary-action:hover { background: #326493; }"
    ".scm-danger-action { color: #e68b8b; }"
    ".scm-danger-action:hover { background: #542a32; color: #ffd0d0; }"
    ".scm-error {"
    "  width: 100%; padding: 8px 10px; gap: 7px; align-items: center;"
    "  background: #3a2026; flex-shrink: 0;"
    "}"
    ".scm-error-icon { color: #e68b8b; font-size: 11px; }"
    ".scm-error-text { color: #f2a0a0; font-size: 11px; text-wrap: wrap; flex-grow: 1; }"
    /* Fixed-size busy indicator living permanently inside .scm-header, next
       to Refresh. Its width/height never change between idle and running —
       only the glyph inside it appears — so a Git operation starting or
       finishing never reflows the branch/remote/tab/file rows beneath the
       header the way a conditionally-rendered banner would. Hover shows
       the specific activity text (e.g. "Pushing changes..."). */
    ".scm-busy-slot {"
    "  width: 16px; height: 16px; justify-content: center; align-items: center;"
    "  flex-shrink: 0;"
    "}"
    ".scm-busy-icon { color: #86bde8; font-size: 11px; }"
    ".scm-no-repository {"
    "  width: 100%; padding: 28px 16px; gap: 10px; align-items: center;"
    "}"
    ".scm-clean-state { width: 100%; padding: 28px 16px; gap: 8px; align-items: center; }"
    ".scm-clean-icon { color: #454556; font-size: 22px; }"
    ".scm-empty {"
    "  color: #727282; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: wrap; text-align: center;"
    "}"
    ".scm-repository {"
    "  width: 100%; padding: 10px 10px; gap: 5px; background: #202029;"
    "}"
    ".scm-branch-row-summary { gap: 7px; align-items: center; }"
    ".scm-branch-icon { color: #7c8494; font-size: 12px; }"
    ".scm-branch-heading {"
    "  color: #d0d0dc; font-size: 13px; font-weight: 600; text-wrap: nowrap;"
    "}"
    ".scm-upstream-row { gap: 9px; align-items: center; }"
    ".scm-upstream { color: #6f8094; font-size: 11px; text-wrap: nowrap; }"
    ".scm-sync-ahead, .scm-sync-behind {"
    "  font-size: 11px; text-wrap: nowrap; font-family: monospace;"
    "}"
    ".scm-sync-ahead { color: #8fd19c; }"
    ".scm-sync-behind { color: #e2b06a; }"
    ".scm-remote-actions {"
    "  width: 100%; height: 32px; padding: 5px 8px; gap: 5px; flex-shrink: 0;"
    "}"
    ".scm-tabs { width: 100%; height: 30px; padding: 0px 6px; gap: 2px; flex-shrink: 0;  }"
    /* flex-grow (not a fixed padding-based width) so three tabs always
       divide the sidebar's actual width evenly and never overflow it —
       a fixed-padding row could clip the last tab on a narrower sidebar
       or once a label grows (e.g. a translated locale). */
    ".scm-tab, .scm-tab-active {"
    "  height: 29px; padding: 0px 6px; gap: 5px; background: transparent;"
    "  color: #777786; border-radius: 0px; font-size: 11px;"
    "  flex-grow: 1; min-width: 0px; justify-content: center;"
    "}"
    ".scm-tab:hover { color: #c0c0cc; background: #252530; }"
    ".scm-tab-active { color: #d8d8e2;  }"
    ".scm-content {"
    "  width: 100%; min-height: 0px; flex-grow: 1; flex-shrink: 1;"
    "  overflow-y: scroll; overflow-x: hidden; gap: 0px; align-items: stretch;"
    "}"
    ".scm-commit-box { width: 100%; padding: 8px; gap: 6px; background: #1b1b22; }"
    ".scm-commit-input, .scm-branch-input {"
    "  width: 100%; height: 30px; padding: 0px 8px; background: #111116;"
    "  color: #d8d8e0;  border-radius: 2px; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "}"
    ".scm-confirm { width: 100%; padding: 8px; gap: 6px; background: #3a2820;  }"
    ".scm-confirm-text { color: #efc098; font-size: 11px; text-wrap: wrap; }"
    ".scm-confirm-actions { width: 100%; gap: 5px; justify-content: flex-end; }"
    ".scm-section-header {"
    "  width: 100%; height: 27px; padding: 0px 6px 0px 8px; align-items: center;"
    "  background: #24242d;  "
    "}"
    ".scm-section-title {"
    "  color: #9292a0; font-size: 11px; font-weight: 600; letter-spacing: 0.3px;"
    "  flex-grow: 1; text-wrap: nowrap;"
    "}"
    ".scm-section-action { height: 20px; font-size: 10px; }"
    /* Every file row shares one fixed left-to-right rhythm: status glyph
       (14px) -> flexible name column -> a fixed rail of 16px icon
       buttons. Keeping the glyph and icon-rail widths constant across
       every row (regardless of file name length) is what makes the list
       align into clean vertical columns instead of each row's actions
       drifting with its name width. */
    ".scm-file-row {"
    "  width: 100%; min-height: 28px; padding: 0px 6px 0px 8px; gap: 4px;"
    "  align-items: center; background: transparent; border-radius: 0px;"
    "}"
    ".scm-file-row:hover { background: #282833; }"
    ".scm-file-name-col {"
    "  min-width: 0px; flex-grow: 1; gap: 5px; align-items: center;"
    "  overflow: hidden; padding: 0px 6px;"
    "}"
    ".scm-file-name {"
    "  color: #c4c4ce; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap; overflow: hidden;"
    "}"
    ".scm-file-name-old {"
    "  color: #6f6f80; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap; overflow: hidden; text-decoration: line-through;"
    "}"
    ".scm-file-rename-arrow { color: #56566a; font-size: 9px; transform: rotate(90deg); }"
    ".scm-status-added, .scm-status-modified, .scm-status-deleted,"
    ".scm-status-renamed, .scm-status-conflict {"
    "  width: 14px; font-size: 11px; font-weight: 700; text-wrap: nowrap;"
    "  text-align: center; flex-shrink: 0;"
    "}"
    ".scm-status-added { color: #77c68a; }"
    ".scm-status-modified { color: #d6b35c; }"
    ".scm-status-deleted { color: #df7777; }"
    ".scm-status-renamed { color: #76a9dc; }"
    ".scm-status-conflict { color: #f05f69; }"
    ".scm-warning { color: #d6b35c; font-size: 11px; padding: 8px; }"
    ".scm-commit-row {"
    "  width: 100%; min-height: 46px; padding: 0px 8px 0px 0px; gap: 4px;"
    "  align-items: center; background: transparent; "
    "}"
    ".scm-commit-row:hover { background: #292934; }"
    /* Graph gutter: width is set inline per-render (lane count varies with
     * the actual repo history), everything inside it is absolutely
     * positioned axis-aligned bars/dots — see git_render_graph_gutter(). */
    ".scm-graph-gutter { flex-shrink: 0; }"
    ".scm-graph-line { background: #3a3a48; border-radius: 0px; }"
    ".scm-graph-line-active { background: #565672; }"
    ".scm-graph-connector { background: #565672; border-radius: 1px; }"
    ".scm-graph-dot {"
    "  background: #6f6f86; border-width: 2px; border-color: #1b1b22;"
    "}"
    ".scm-graph-dot-merge { background: #7c9cd6; }"
    ".scm-commit-info {"
    "  min-width: 0px; flex-grow: 1; gap: 3px; padding: 7px 0px;"
    "  align-items: stretch;"
    "}"
    ".scm-commit-subject {"
    "  color: #ceced8; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap; overflow: hidden;"
    "}"
    ".scm-commit-meta-row { gap: 9px; align-items: center; }"
    ".scm-commit-hash {"
    "  color: #8896b8; font-size: 10px; font-family: monospace; text-wrap: nowrap;"
    "}"
    ".scm-commit-meta { color: #676779; font-size: 10px; text-wrap: nowrap; overflow: hidden; }"
    ".scm-submodule-row { width: 100%; min-height: 40px; padding: 5px 9px; gap: 8px; align-items: center; }"
    ".scm-submodule-info { min-width: 0px; flex-grow: 1; gap: 2px; align-items: stretch; }"
    ".scm-submodule-path { color: #c8c8d2; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS "; text-wrap: nowrap; overflow: hidden; }"
    ".scm-submodule-clean,.scm-submodule-modified,.scm-submodule-warning,.scm-submodule-conflict { font-size: 10px; text-wrap: nowrap; }"
    ".scm-submodule-clean { color: #6f8094; }"
    ".scm-submodule-modified { color: #d6b35c; }"
    ".scm-submodule-warning { color: #e2b06a; }"
    ".scm-submodule-conflict { color: #f05f69; }"
    ".scm-branch-create { width: 100%; padding: 8px; gap: 5px; align-items: center; }"
    ".scm-branch-row, .scm-branch-row-current {"
    "  width: 100%; min-height: 38px; padding: 5px 9px; gap: 8px;"
    "  align-items: center; background: transparent; "
    "}"
    ".scm-branch-row:hover { background: #292934; }"
    ".scm-branch-row-current { background: #1c3048; }"
    ".scm-branch-current-icon {"
    "  width: 13px; color: #6fa8dc; font-size: 11px; flex-shrink: 0;"
    "}"
    ".scm-branch-info { min-width: 0px; flex-grow: 1; gap: 2px; align-items: stretch; }"
    ".scm-branch-name {"
    "  color: #c8c8d2; font-size: " SOL_UI_BOOT_FONT_SIZE_PX_CSS ";"
    "  text-wrap: nowrap; overflow: hidden;"
    "}"
    ".scm-branch-upstream { color: #66667a; font-size: 10px; text-wrap: nowrap; overflow: hidden; }"
    ".scm-view {"
    "  width: 100%; height: 100%; min-height: 0px; padding: 8px 10px; gap: 0px;"
    "  background: #111116; overflow-y: scroll; overflow-x: scroll; align-items: stretch;"
    "}"
    ".scm-view-text, .scm-view-added, .scm-view-removed, .scm-view-hunk,"
    ".scm-view-heading, .scm-view-meta { font-family: monospace; font-size: 11px; text-wrap: nowrap; }"
    ".scm-view-text { color: #b8b8c2; }"
    ".scm-view-added { color: #8fd19c; background: #14251a; }"
    ".scm-view-removed { color: #e28b8b; background: #2a1719; }"
    ".scm-view-hunk { color: #80b7e5; background: #182636; }"
    ".scm-view-heading { color: #d8c47a; }"
    ".scm-view-meta { color: #737386; }"

    /* ===== Minimal glass theme overrides ===== */
    ".tree-panel, .plugin-side-panel {"
    "  background: rgba(5, 11, 19, " SOL_UI_SURFACE_CHROME_ALPHA_CSS ");"
    "}"
    ".tree-section-header {"
    "  height: 30px; padding: 0px 12px; background: transparent;"
    "}"
    ".tree-section-title { color: #8997aa; letter-spacing: 0.9px; }"
    ".tree-scroll-area { padding: 3px 5px 6px 5px; }"
    ".tree-row { height: 24px; padding: 0px 8px; border-radius: 0px; }"
    ".tree-row:hover { background: rgba(128, 159, 197, 0.10); }"
    ".tree-root-row {"
    "  height: 28px; padding: 0px 8px; background: transparent;"
    "}"
    ".tree-sticky-row {"
    "  background: rgba(12, 23, 38, 0.82);"
    "  border-radius: 0px;"
    "}"
    ".tree-sticky-row:hover { background: rgba(116, 151, 194, 0.14); }"
    ".tree-arrow { color: #718095; }"
    ".tree-arrow-open { color: #8fb5df; }"
    ".tree-name { color: #c1c9d4; }"
    ".tree-name-dir { color: #e0e5eb; }"

    ".buffer-pane, .buffer-pane-active { background: transparent; }"
    ".buffer-tabs-row {"
    "  height: 19px; padding: 1px 3px; gap: 1px; align-items: center;"
    "  background: rgba(5, 12, 21, " SOL_UI_SURFACE_RAISED_ALPHA_CSS "); "
    "}"
    ".buffer-tab {"
    "  height: 17px; padding: 0px 2px 0px 7px; background: transparent;"
    "  border-radius: 0px;  "
    "}"
    ".buffer-tab:hover { background: rgba(118, 151, 192, 0.14); }"
    ".buffer-tab-active {"
    "  background: rgba(112, 157, 207, 0.38); "
    "}"
    ".buffer-tab-text { color: #8d99a9; }"
    ".buffer-tab-text-active { color: #f0f4f8; }"
    ".buffer-tab-dirty { color: #e0a030; }"
    ".buffer-tab-dirty-active { color: #f0b840; }"
    ".buffer-tab-close { border-radius: 0px; }"
    ".buffer-tab-close:hover { background: rgba(220, 92, 106, 0.20); }"
    ".buffer-body {"
    "  background: rgba(5, 10, 18, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); "
    "}"
    ".buffer-gutter-col { background: rgba(8, 16, 27, 0.68);  }"
    ".buffer-scrollbar { width: 9px; background: rgba(7, 10, 15, 0.28);  }"
    ".buffer-scrollbar-spacer { width: 9px; }"
    ".buffer-hscrollbar { height: 9px; background: rgba(7, 10, 15, 0.28);  }"
    ".buffer-hscrollbar-spacer { height: 9px; }"
    ".buffer-scrollbar-thumb, .buffer-scrollbar-thumb-active,"
    ".buffer-hscrollbar-thumb, .buffer-hscrollbar-thumb-active {"
    "  background: rgba(129, 148, 172, 0.40); border-radius: 0px;"
    "   width: 9px;"
    "}"
    ".buffer-hscrollbar-thumb, .buffer-hscrollbar-thumb-active { height: 9px; }"
    ".buffer-scrollbar-thumb:hover, .buffer-scrollbar-thumb-active,"
    ".buffer-hscrollbar-thumb:hover, .buffer-hscrollbar-thumb-active {"
    "  background: rgba(150, 174, 202, 0.58);"
    "}"

    ".status-bar {"
    "  height: 22px; padding: 0px 10px; background: rgba(3, 8, 15, " SOL_UI_SURFACE_CHROME_ALPHA_CSS ");"
    "}"
    ".status-bar-badge { border-radius: 0px; }"
    ".status-bar-text { color: #8795aa; }"
    ".status-bar-badge-key { background: rgba(73, 126, 184, 0.34); }"
    ".status-bar-badge-command { background: rgba(67, 142, 116, 0.30); }"
    ".status-bar-badge-leader { background: rgba(175, 133, 61, 0.30); }"

    ".cf-panel {"
    "  background: rgba(6, 14, 24, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); "
    "  border-radius: 0px; shadow-offset-y: 6px; shadow-blur: 18px;"
    "  shadow-color: rgba(0, 0, 0, 0.38);"
    "}"
    ".cf-row { border-radius: 0px;  }"
    ".cf-row:hover { background: transparent; }"
    ".cf-row-key { background: rgba(100, 142, 192, 0.16);  border-radius: 0px; }"

    ".fp-root, .search-root-window { background: rgba(6, 14, 24, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); }"
    ".fp-toolbar, .fp-footer, .fp-colhdr, .search-header, .search-footer {"
    "  background: rgba(23, 29, 41, " SOL_UI_SURFACE_RAISED_ALPHA_CSS ");  "
    "}"
    ".fp-list, .search-results { background: rgba(9, 13, 20, " SOL_UI_SURFACE_WELL_ALPHA_CSS "); }"
    ".fp-row, .search-result { border-radius: 0px;  }"
    ".fp-row:hover, .search-result:hover { background: rgba(117, 151, 193, 0.12); }"
    ".fp-row-selected, .search-result-selected {"
    "  background: rgba(77, 130, 190, 0.24); "
    "}"
    ".fp-new-folder-input, .search-input {"
    "  background: rgba(7, 10, 16, " SOL_UI_SURFACE_WELL_ALPHA_CSS "); "
    "   border-radius: 0px; color: #dce2ea;"
    "}"
    ".fp-action-new-folder, .fp-nf-create, .fp-nf-cancel {"
    "  border-radius: 0px;  background: rgba(92, 124, 166, 0.13);"
    "}"

    ".welcome-pane {"
    "  background: rgba(5, 11, 20, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); padding: 60px 72px; align-items: center;"
    "}"
    ".welcome-content {"
    "  width: 100%; max-width: 1120px; gap: 0px; align-items: stretch;"
    "}"
    ".welcome-title { color: #e1e6ed; font-size: 24px; }"
    ".welcome-subtitle, .welcome-section-label { color: #748195; }"
    ".welcome-desc { color: #9aa6b8; }"
    ".welcome-hr { background: rgba(112, 139, 172, 0.24); }"
    ".welcome-btn {"
    "  border-radius: 0px; "
    "  background: rgba(104, 132, 166, 0.10); color: #cbd5e1;"
    "}"
    ".welcome-btn-primary {"
    "  border-radius: 0px; "
    "  background: rgba(83, 139, 202, 0.24); color: #e5edf6;"
    "}"
    ".welcome-btn:hover, .welcome-btn-primary:hover { background: rgba(91, 151, 218, 0.25); }"

    ".pm-root, .sw-root { background: rgba(6, 10, 16, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); }"
    ".pm-left, .sw-left {"
    "  background: rgba(15, 22, 33, " SOL_UI_SURFACE_RAISED_ALPHA_CSS "); "
    "}"
    ".pm-search-row { background: rgba(24, 31, 43, " SOL_UI_SURFACE_RAISED_ALPHA_CSS ");   }"
    ".pm-search-input, .sw-scale-input, .sw-select {"
    "  background: rgba(7, 10, 16, " SOL_UI_SURFACE_WELL_ALPHA_CSS ");   border-radius: 0px;"
    "}"
    ".pm-item, .sw-tab-btn {  border-radius: 0px; }"
    ".pm-item:hover, .sw-tab-btn:hover { background: rgba(117, 151, 193, 0.11); }"
    ".pm-item-selected, .sw-tab-btn-active {"
    "  background: rgba(78, 132, 193, 0.22); "
    "}"
    ".pm-right, .sw-right { background: rgba(7, 10, 16, 0.56); }"
    ".pm-btn, .pm-btn-enable, .pm-btn-disable {"
    "  border-radius: 0px;  background: rgba(93, 126, 168, 0.13);"
    "}"
    ".pm-btn:hover { background: rgba(110, 155, 208, 0.20); }"
    ".sw-hr, .pm-hr { background: #344154; }"

    ".scm-root, .scm-view { background: rgba(10, 15, 23, " SOL_UI_SURFACE_CHROME_ALPHA_CSS "); }"
    ".scm-toolbar, .scm-repository, .scm-commit-box, .scm-section-header {"
    "  background: rgba(20, 28, 40, " SOL_UI_SURFACE_RAISED_ALPHA_CSS "); "
    "}"
    ".scm-tab, .scm-tab-active, .scm-file-row, .scm-commit-row,"
    ".scm-branch-row, .scm-branch-row-current { border-radius: 0px; }"
    ".scm-file-row:hover, .scm-commit-row:hover, .scm-branch-row:hover {"
    "  background: rgba(117, 151, 193, 0.11);"
    "}"
    ".scm-commit-input, .scm-branch-input {"
    "  background: rgba(7, 10, 16, " SOL_UI_SURFACE_WELL_ALPHA_CSS ");   border-radius: 0px;"
    "}"

    /* High-contrast editor typography over the animated glass canvas. */
    ".buffer-line, .buffer-body-text, .hl-plain { color: #d8dee9; }"
    ".buffer-gutter-line { color: #647084; }"
    ".hl-comment { color: #8293a0; }"
    ".hl-keyword, .hl-macro { color: #d49bea; }"
    ".hl-string, .hl-regex { color: #b9dc8c; }"
    ".hl-number, .hl-constant, .hl-escape { color: #f1b784; }"
    ".hl-function, .hl-constructor { color: #82b9ea; }"
    ".hl-type, .hl-namespace { color: #7fd0c7; }"
    ".hl-property, .hl-attribute, .hl-parameter { color: #c5ccd8; }"
    ".hl-operator, .hl-label { color: #aeb8c7; }"
    ".hl-tag { color: #ee8d9a; }"

    /* ===== Floating rounded glass composition ===== */
    ".workspace-main-content { padding: " SOL_UI_PANEL_MARGIN_PX_CSS "; }"
    ".tree-panel, .plugin-side-panel, .buffer-pane, .term-panel, .welcome-pane {"
    "  border-radius: " SOL_UI_PANEL_RADIUS_PX_CSS "; overflow: hidden;"
    "}"
    /* Focused-panel indicator: a thin inset accent border on whichever
       top-level panel currently owns keyboard focus (tree/plugin
       sidebar, the active buffer pane, or the terminal) — see
       SolUIFocusedPanel. A real border (not a shadow/glow): this
       engine's shadow SDF returns full opacity for every fragment
       inside the shape (it only fades OUTSIDE the box), so a
       zero-offset "glow" shadow paints as a solid rectangle, and the
       soft fringe that should extend past the panel edge gets clipped
       by the workspace's own overflow:hidden gutter anyway. The uniform
       border render mode is a true inset ring — always contained within
       the node's own bounds and immune to both problems. */
    ".tree-panel-focused, .plugin-side-panel-focused,"
    ".buffer-pane-focused, .term-panel-focused {"
    "  border-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "  border-width: " SOL_UI_FOCUS_BORDER_WIDTH_PX_CSS ";"
    "  border-color: " SOL_UI_FOCUS_BORDER_COLOR_CSS ";"
    "}"
    ".buffer-tabs-row {"
    "  padding: 1px 4px; gap: 3px; overflow: hidden;"
    "  border-top-left-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "  border-top-right-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "}"
    ".buffer-body, .buffer-scroll-row {"
    "  overflow: hidden;"
    "  border-bottom-left-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "  border-bottom-right-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "}"
    ".buffer-gutter-col {"
    "  border-bottom-left-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "}"
    ".buffer-tab { border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; }"
    ".buffer-tab-close, .term-tab-close { border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; }"
    ".buffer-scrollbar, .buffer-hscrollbar { background: transparent; }"
    ".buffer-scrollbar-thumb, .buffer-scrollbar-thumb-active,"
    ".buffer-hscrollbar-thumb, .buffer-hscrollbar-thumb-active {"
    "  border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS ";"
    "}"
    ".tree-scroll-area { padding: 5px 6px 8px 6px; }"
    ".tree-row, .tree-root-row, .tree-sticky-row {"
    "  border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; min-width: 0px; overflow: hidden;"
    "}"
    /* Terminal tab strip mirrors the buffer tab strip: a slightly taller
       row (19px + 1px padding, matching .buffer-tabs-row) holding inset
       pill tabs (17px), not tabs flush to the row's own edges. */
    ".term-header {"
    "  height: 19px; padding: 1px 3px; gap: 1px;"
    "  border-top-left-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "  border-top-right-radius: " SOL_UI_PANEL_RADIUS_PX_CSS ";"
    "}"
    ".term-tab, .term-tab-active {"
    "  height: 17px; border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS ";"
    "}"
    ".status-bar {"
    "  width: auto; height: 22px; margin: 0px " SOL_UI_PANEL_MARGIN_PX_CSS
    " 8px " SOL_UI_PANEL_MARGIN_PX_CSS "; padding: 0px 8px;"
    "  flex-grow: 1; flex-shrink: 1; border-radius: " SOL_UI_PILL_RADIUS_PX_CSS ";"
    "}"
    ".status-bar-badge { border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; }"
    ".cf-panel { border-radius: " SOL_UI_PANEL_RADIUS_PX_CSS "; padding: 8px; gap: 3px; }"
    ".cf-row, .cf-row-key { border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; }"
    ".ca-popup-card, .ca-select-popup, .ca-tooltip, .ca-context-menu,"
    ".ca-menubar-popup { border-radius: " SOL_UI_PANEL_RADIUS_PX_CSS "; overflow: hidden; }"
    ".ca-popup-btn, .ca-titlebar-menu-item, .ca-titlebar-control,"
    ".ca-overlay-hover, .fp-row, .fp-up-btn, .fp-crumb-btn,"
    ".fp-colhdr-btn, .fp-colhdr-btn-end, .fp-action-cancel,"
    ".fp-action-primary, .fp-action-new-folder, .fp-nf-create, .fp-nf-cancel,"
    ".search-result, .pm-item, .pm-btn, .pm-btn-enable, .pm-btn-disable,"
    ".sw-tab-btn, .welcome-btn, .welcome-btn-primary,"
    ".scm-header-action, .scm-action, .scm-icon-action, .scm-header-icon-action,"
    ".scm-action-icon, .scm-section-action, .scm-primary-action, .scm-danger-action,"
    ".scm-file-row, .scm-commit-row, .scm-branch-row, .scm-branch-row-current,"
    ".scm-tab, .scm-tab-active {"
    "  border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS ";"
    "}"
    ".fp-new-folder-input, .search-input, .pm-search-input, .sw-scale-input,"
    ".sw-select, .scm-commit-input, .scm-branch-input {"
    "  border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS ";"
    "}"
    ".pm-badge { border-radius: " SOL_UI_CONTROL_RADIUS_PX_CSS "; }";

#endif /* SOL_UI_STYLE_H */
